// SPDX-License-Identifier: GPL-3.0-or-later
// clang-format off
// source line, original position xyz, original rotation xyz, variant, scale,
// replacement ODEF name, replacement yaw
CITYWORLD_NEOQ_TREE_REPLACEMENT(9U, 1777.425049f, 0.1f, 2232.668945f, 0.0f, 90.0f, 0.0f, "rorng_city_neoq_tree_windswept", 1.02212f, "rorng_city_neoq_tree_instance_00", 222.451f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(10U, 1760.757202f, 0.1f, 2232.668945f, 0.0f, -158.0f, 0.0f, "rorng_city_neoq_tree_round", 1.0035f, "rorng_city_neoq_tree_instance_01", 305.903f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(11U, 1742.089355f, 0.1f, 2232.668945f, 0.0f, -139.5f, 0.0f, "rorng_city_neoq_tree_windswept", 0.95385f, "rorng_city_neoq_tree_instance_02", 259.129f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(12U, 1721.921509f, 0.1f, 2232.668945f, 0.0f, 80.0f, 0.0f, "rorng_city_neoq_tree_columnar", 0.97434f, "rorng_city_neoq_tree_instance_03", 98.223f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(13U, 1703.253662f, 0.1f, 2232.668945f, 0.0f, 21.5f, 0.0f, "rorng_city_neoq_tree_round", 0.99675f, "rorng_city_neoq_tree_instance_04", 181.417f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(14U, 1683.585815f, 0.1f, 2232.668945f, 0.0f, -109.5f, 0.0f, "rorng_city_neoq_tree_columnar", 0.99205f, "rorng_city_neoq_tree_instance_05", 237.426f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(15U, 1666.417969f, 0.1f, 2232.668945f, 0.0f, -116.5f, 0.0f, "rorng_city_neoq_tree_round", 1.02293f, "rorng_city_neoq_tree_instance_06", 317.23f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(16U, 1645.750122f, 0.1f, 2232.668945f, 0.0f, 25.0f, 0.0f, "rorng_city_neoq_tree_windswept", 0.99205f, "rorng_city_neoq_tree_instance_07", 143.514f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(17U, 1626.582275f, 0.1f, 2232.668945f, 0.0f, -116.0f, 0.0f, "rorng_city_neoq_tree_columnar", 1.058f, "rorng_city_neoq_tree_instance_08", 132.039f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(18U, 1777.425049f, 0.1f, 2046.000977f, 0.0f, -180.0f, 0.0f, "rorng_city_neoq_tree_columnar", 0.9917f, "rorng_city_neoq_tree_instance_09", 9.163f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(19U, 1760.757202f, 0.1f, 2046.000977f, 0.0f, -154.5f, 0.0f, "rorng_city_neoq_tree_windswept", 0.95647f, "rorng_city_neoq_tree_instance_10", 263.177f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(20U, 1742.089355f, 0.1f, 2046.000977f, 0.0f, -94.5f, 0.0f, "rorng_city_neoq_tree_windswept", 1.05474f, "rorng_city_neoq_tree_instance_11", 276.213f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(21U, 1703.253662f, 0.1f, 2046.000977f, 0.0f, 137.0f, 0.0f, "rorng_city_neoq_tree_windswept", 0.98636f, "rorng_city_neoq_tree_instance_12", 189.965f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(22U, 1683.585815f, 0.1f, 2046.000977f, 0.0f, 108.5f, 0.0f, "rorng_city_neoq_tree_windswept", 0.95579f, "rorng_city_neoq_tree_instance_13", 163.367f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(23U, 1666.417969f, 0.1f, 2046.000977f, 0.0f, -153.5f, 0.0f, "rorng_city_neoq_tree_round", 1.04347f, "rorng_city_neoq_tree_instance_14", 79.579f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(24U, 1645.750122f, 0.1f, 2046.000977f, 0.0f, 43.0f, 0.0f, "rorng_city_neoq_tree_windswept", 1.01262f, "rorng_city_neoq_tree_instance_15", 127.112f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(25U, 1722.910278f, -0.054961f, 2044.339844f, 0.0f, 64.0f, 0.0f, "rorng_city_neoq_tree_windswept", 1.01194f, "rorng_city_neoq_tree_instance_16", 116.856f)
CITYWORLD_NEOQ_TREE_REPLACEMENT(26U, 1629.423096f, -0.074142f, 2046.764160f, 0.0f, -72.0f, 0.0f, "rorng_city_neoq_tree_windswept", 0.98921f, "rorng_city_neoq_tree_instance_17", 188.52f)
// clang-format on
