/// \title CityWorld Neo-to-NeoQ2.0 full bridge drive gate
/// \brief Drives the packaged DAF across both authenticated city-road seams.

const int APP_STATE_SIMULATION = 2;
const int SIM_STATE_PAUSED = 2;
const int64 ACTOR_ID = 2026072902;
const int64 REVERSE_ACTOR_ID = 2026072903;
const uint64 MAX_PHYSICS_STEPS = 680000;
const uint64 MAX_NO_PROGRESS_STEPS = 80000;
const string VEHICLE = "b6b0UID-semi.truck";

const float ROUTE_LENGTH_M = 3076.132100441f;
const float SOURCE_SEAM_STATION = 0.0f;
const float SOURCE_SEAM_X_M = 3790.970703f;
const float MIDPOINT_STATION = 1538.066050221f;
const float DESTINATION_SEAM_STATION = ROUTE_LENGTH_M;
const float PASS_DESTINATION_X_M = 6877.0f;
const float REVERSE_PASS_STATION = 3036.132100441f;
const float LOOKAHEAD_M = 30.0f;
const float MAX_PATH_ERROR_M = 2.5f;
const float MAX_VERTICAL_ERROR_M = 4.0f;
const float MAX_REGRESSION_M = 8.0f;
const float PROGRESS_WINDOW_M = 5.0f;
const float DESTINATION_LANE_SHIFT_START_M = 2200.0f;
const float DESTINATION_LANE_SHIFT_END_M = 2600.0f;
const float DESTINATION_LANE_CROSS_TRACK_M = 5.8f;
const float DESTINATION_LANE_SAFE_MIN_LOCAL_Z_M = 1.95f;
const float DESTINATION_LANE_SAFE_MAX_LOCAL_Z_M = 6.30f;

// Samples 0..79 are the exact v4 overlay route points generated by
// tools/cityworld_neoq_intercity_bridge.py with surface_offset_m=0.08. Point
// zero starts flush at NeoQueretaro's decoded mesh edge and point 79 ends
// flush at NeoQ2.0's west distributor seam. Samples 80..81 are runtime-only
// continuations along the preserved positive-local-z destination carriageway.
// The forward truck crosses both zero-overlap seams, then a separately spawned
// westbound truck proves the destination seam in the opposite direction.
array<vector3> gPath = {
    vector3(3790.970703000f, 0.100000000f, 3993.104004000f),
    vector3(3830.970497719f, 0.100000000f, 3993.221193040f),
    vector3(3870.969932807f, 1.430052995f, 3993.432756338f),
    vector3(3910.969157867f, 4.180210077f, 3993.681695191f),
    vector3(3950.968244180f, 6.930468390f, 3993.952208108f),
    vector3(3990.967229427f, 8.180825080f, 3994.237176793f),
    vector3(4030.966136955f, 8.181277289f, 3994.532669098f),
    vector3(4070.964987513f, 8.181822163f, 3994.836240814f),
    vector3(4110.963784330f, 8.182456847f, 3995.146249174f),
    vector3(4150.962544713f, 8.183178485f, 3995.461526847f),
    vector3(4190.961264746f, 8.183984221f, 3995.781208483f),
    vector3(4230.959956575f, 8.184871200f, 3996.104631318f),
    vector3(4270.958624091f, 8.185836567f, 3996.431273928f),
    vector3(4310.957269383f, 8.186877465f, 3996.760717005f),
    vector3(4350.955889681f, 8.187991040f, 3997.092617021f),
    vector3(4390.954495804f, 8.189174437f, 3997.426688168f),
    vector3(4430.953084800f, 8.190424799f, 3997.762689158f),
    vector3(4470.951658578f, 8.191739270f, 3998.100413913f),
    vector3(4510.950219671f, 8.193114997f, 3998.439684475f),
    vector3(4550.948770367f, 8.194549123f, 3998.780345642f),
    vector3(4590.947308326f, 8.196038792f, 3999.122260803f),
    vector3(4630.945837314f, 8.197581150f, 3999.465308791f),
    vector3(4670.944356948f, 8.199173341f, 3999.809381228f),
    vector3(4710.942869586f, 8.200812508f, 4000.154380524f),
    vector3(4750.941375203f, 8.202495798f, 4000.500218153f),
    vector3(4790.939874198f, 8.204220354f, 4000.846813305f),
    vector3(4830.938365650f, 8.205983321f, 4001.194091728f),
    vector3(4870.936852832f, 8.207781843f, 4001.541984822f),
    vector3(4910.935335775f, 8.209613065f, 4001.890428764f),
    vector3(4950.933813909f, 8.211474131f, 4002.239363845f),
    vector3(4990.932287748f, 8.213362187f, 4002.588733891f),
    vector3(5030.930758753f, 8.215274376f, 4002.938485745f),
    vector3(5070.929227410f, 8.217207842f, 4003.288568797f),
    vector3(5110.927692440f, 8.219159732f, 4003.638934576f),
    vector3(5150.926156224f, 8.221127188f, 4003.989536438f),
    vector3(5190.924617836f, 8.223107356f, 4004.340329174f),
    vector3(5230.923078603f, 8.225097380f, 4004.691268761f),
    vector3(5270.921538133f, 8.227094405f, 4005.042312042f),
    vector3(5310.919997278f, 8.229095575f, 4005.393416489f),
    vector3(5350.918456274f, 8.231098035f, 4005.744539931f),
    vector3(5390.916915470f, 8.233098929f, 4006.095640309f),
    vector3(5430.915375117f, 8.235095401f, 4006.446675429f),
    vector3(5470.913835898f, 8.237084597f, 4006.797602711f),
    vector3(5510.912297654f, 8.239063661f, 4007.148378929f),
    vector3(5550.910761684f, 8.241029736f, 4007.498959959f),
    vector3(5590.909227012f, 8.242979969f, 4007.849300463f),
    vector3(5630.907695993f, 8.244911503f, 4008.199353638f),
    vector3(5670.906167337f, 8.246821483f, 4008.549070820f),
    vector3(5710.904642007f, 8.248707054f, 4008.898401176f),
    vector3(5750.903120333f, 8.250565359f, 4009.247291269f),
    vector3(5790.901602991f, 8.252393544f, 4009.595684608f),
    vector3(5830.900091037f, 8.254188752f, 4009.943521126f),
    vector3(5870.898583607f, 8.255948129f, 4010.290736563f),
    vector3(5910.897082849f, 8.257668820f, 4010.637261800f),
    vector3(5950.895589021f, 8.259347968f, 4010.983022007f),
    vector3(5990.894101377f, 8.260982717f, 4011.327935669f),
    vector3(6030.892622713f, 8.262570214f, 4011.671913473f),
    vector3(6070.891151565f, 8.264107602f, 4012.014856831f),
    vector3(6110.889691039f, 8.265592025f, 4012.356656255f),
    vector3(6150.888241751f, 8.267020628f, 4012.697189181f),
    vector3(6190.886805082f, 8.268390556f, 4013.036317384f),
    vector3(6230.885379536f, 8.269698954f, 4013.373883625f),
    vector3(6270.883969861f, 8.270942965f, 4013.709707504f),
    vector3(6310.882578296f, 8.272119734f, 4014.043579884f),
    vector3(6350.881202828f, 8.273226407f, 4014.375255629f),
    vector3(6390.879849590f, 8.274260126f, 4014.704443956f),
    vector3(6430.878515962f, 8.275218038f, 4015.030794906f),
    vector3(6470.877213354f, 8.276097285f, 4015.353880680f),
    vector3(6510.875936122f, 8.276895014f, 4015.673168083f),
    vector3(6550.874699569f, 8.277608368f, 4015.987977919f),
    vector3(6590.873500316f, 8.278234492f, 4016.297420803f),
    vector3(6630.872353119f, 8.278770531f, 4016.600292610f),
    vector3(6667.003473573f, 8.279174920f, 4016.866827207f),
    vector3(6670.871271105f, 8.265414062f, 4016.894890913f),
    vector3(6710.870263072f, 6.805204816f, 4017.178666295f),
    vector3(6750.869361284f, 3.989943152f, 4017.447479434f),
    vector3(6790.868601538f, 1.317526783f, 4017.693725326f),
    vector3(6827.000205281f, 0.200000000f, 4017.882810960f),
    vector3(6830.868064918f, 0.200000000f, 4017.900037554f),
    vector3(6867.000000000f, 0.200000000f, 4018.000000000f),
    vector3(6877.000000000f, 0.200000000f, 4018.000000000f),
    vector3(6887.000000000f, 0.200000000f, 4018.000000000f)
};

array<float> gStation;

enum RuntimeState
{
    WAITING_FOR_TERRAIN = 0,
    WAITING_FOR_PAUSE,
    WAITING_FOR_ACTOR,
    DRIVING_FORWARD,
    BRAKING_FOR_REVERSE,
    WAITING_FOR_REVERSE_ACTOR,
    DRIVING_REVERSE,
    FINISHED
}

RuntimeState gState = WAITING_FOR_TERRAIN;
BeamClass@ gActor;
EngineClass@ gEngine;
CVarClass@ gAppState;
CVarClass@ gSimState;
bool gActorSpawned = false;
int64 gExpectedActorId = ACTOR_ID;
bool gSourceSeam = false;
bool gMidpoint = false;
bool gDestinationSeam = false;
bool gReverseDestinationSeam = false;
bool gHasLastPosition = false;
uint gDrivingFrames = 0;
float gDistance = 0.0f;
float gForwardDistance = 0.0f;
float gForwardDestinationStation = 0.0f;
float gForwardDestinationX = 0.0f;
float gForwardDestinationLocalZ = 0.0f;
float gReverseDestinationLocalZ = 0.0f;
float gClosestStation = 0.0f;
float gClosestCrossTrack = 0.0f;
float gClosestSurfaceY = 0.1f;
float gReferenceCrossTrack = 0.0f;
float gReferenceHeight = 0.0f;
float gMaximumPathError = 0.0f;
float gMaximumVerticalError = 0.0f;
float gMaximumRegression = 0.0f;
float gPreviousProgress = 0.0f;
float gProgressCheckpointStation = 0.0f;
uint64 gProgressCheckpointStep = 0;
vector3 gLastPosition;

float Clamp(float value, float minimum, float maximum)
{
    if (value < minimum)
        return minimum;
    if (value > maximum)
        return maximum;
    return value;
}

float Distance2D(
    float firstX,
    float firstZ,
    float secondX,
    float secondZ)
{
    const float dx = firstX - secondX;
    const float dz = firstZ - secondZ;
    return sqrt(dx * dx + dz * dz);
}

float WrapAngle(float value)
{
    while (value > 3.141592654f)
        value -= 6.283185307f;
    while (value < -3.141592654f)
        value += 6.283185307f;
    return value;
}

void InitializeStations()
{
    gStation.resize(82);
    gStation[0] = 0.0f;
    for (uint index = 1; index <= 71; index++)
        gStation[index] = 40.0f * float(index);
    gStation[72] = 2876.132100441f;
    gStation[73] = 2880.0f;
    gStation[74] = 2920.0f;
    gStation[75] = 2960.0f;
    gStation[76] = 3000.0f;
    gStation[77] = 3036.132100441f;
    gStation[78] = 3040.0f;
    gStation[79] = DESTINATION_SEAM_STATION;
    gStation[80] = DESTINATION_SEAM_STATION + 10.0f;
    gStation[81] = DESTINATION_SEAM_STATION + 20.0f;
}

bool ValidateRouteContract()
{
    if (gPath.length() != 82 || gStation.length() != gPath.length())
        return false;
    for (uint index = 0; index + 1 < gStation.length(); index++)
    {
        if (gStation[index + 1] <= gStation[index])
            return false;
    }
    if (
        Distance2D(gPath[0].x, gPath[0].z, 3790.970703f, 3993.104004f)
            > 0.01f ||
        Distance2D(gPath[79].x, gPath[79].z, 6867.0f, 4018.0f)
            > 0.01f ||
        Distance2D(gPath[80].x, gPath[80].z, 6877.0f, 4018.0f)
            > 0.01f ||
        Distance2D(gPath[81].x, gPath[81].z, 6887.0f, 4018.0f)
            > 0.01f)
    {
        return false;
    }
    return (
        abs(gStation[0] - SOURCE_SEAM_STATION) <= 0.01f &&
        abs(gStation[79] - DESTINATION_SEAM_STATION) <= 0.01f &&
        abs(gStation[79] - ROUTE_LENGTH_M) <= 0.01f &&
        abs(gStation[81] - ROUTE_LENGTH_M - 20.0f) <= 0.01f);
}

void FindClosestPath(const vector3 &in position)
{
    float bestSquared = 1000000000.0f;
    for (uint index = 0; index + 1 < gPath.length(); index++)
    {
        const float dx = gPath[index + 1].x - gPath[index].x;
        const float dz = gPath[index + 1].z - gPath[index].z;
        const float lengthSquared = dx * dx + dz * dz;
        if (lengthSquared <= 0.000001f)
            continue;
        const float fraction = Clamp(
            (
                (position.x - gPath[index].x) * dx +
                (position.z - gPath[index].z) * dz
            ) / lengthSquared,
            0.0f,
            1.0f);
        const float projectedX = gPath[index].x + fraction * dx;
        const float projectedZ = gPath[index].z + fraction * dz;
        const float offsetX = position.x - projectedX;
        const float offsetZ = position.z - projectedZ;
        const float squared = offsetX * offsetX + offsetZ * offsetZ;
        if (squared >= bestSquared)
            continue;
        bestSquared = squared;
        const float length = sqrt(lengthSquared);
        gClosestStation =
            gStation[index] +
            fraction * (gStation[index + 1] - gStation[index]);
        gClosestCrossTrack = (dx * offsetZ - dz * offsetX) / length;
        gClosestSurfaceY =
            gPath[index].y +
            fraction * (gPath[index + 1].y - gPath[index].y);
    }
}

vector3 SamplePath(float station)
{
    if (station <= gStation[0])
        return gPath[0];
    const uint last = gStation.length() - 1;
    if (station >= gStation[last])
    {
        const vector3 delta = gPath[last] - gPath[last - 1];
        const float segmentLength =
            gStation[last] - gStation[last - 1];
        return (
            gPath[last] +
            delta * ((station - gStation[last]) / segmentLength)
        );
    }
    for (uint index = 0; index < last; index++)
    {
        if (station > gStation[index + 1])
            continue;
        const float fraction =
            (station - gStation[index]) /
            (gStation[index + 1] - gStation[index]);
        return gPath[index] + (gPath[index + 1] - gPath[index]) * fraction;
    }
    return gPath[last];
}

vector3 PathTangent(float station)
{
    const vector3 before = SamplePath(station - 1.0f);
    const vector3 after = SamplePath(station + 1.0f);
    vector3 tangent(after.x - before.x, 0.0f, after.z - before.z);
    const float length = sqrt(tangent.x * tangent.x + tangent.z * tangent.z);
    if (length > 0.000001f)
    {
        tangent.x /= length;
        tangent.z /= length;
    }
    return tangent;
}

float TargetCrossTrack(float station)
{
    const float linear = Clamp(
        (
            station - DESTINATION_LANE_SHIFT_START_M
        ) / (
            DESTINATION_LANE_SHIFT_END_M -
            DESTINATION_LANE_SHIFT_START_M
        ),
        0.0f,
        1.0f);
    const float eased = linear * linear * (3.0f - 2.0f * linear);
    return (
        gReferenceCrossTrack +
        eased * (
            DESTINATION_LANE_CROSS_TRACK_M -
            gReferenceCrossTrack
        ));
}

void ApplySteer(float steer)
{
    if (steer >= 0.0f)
    {
        gActor.setEventSimulatedValue(EV_TRUCK_STEER_LEFT, steer);
        gActor.setEventSimulatedValue(EV_TRUCK_STEER_RIGHT, 0.0f);
    }
    else
    {
        gActor.setEventSimulatedValue(EV_TRUCK_STEER_LEFT, 0.0f);
        gActor.setEventSimulatedValue(EV_TRUCK_STEER_RIGHT, -steer);
    }
}

void ClearControls()
{
    if (@gActor != null)
        gActor.clearEventSimulatedValues();
}

void Finish()
{
    ClearControls();
    console.cVarSet("sim_deterministic_fixed_steps_per_frame", "0");
    console.cVarSet("ui_hide_gui", "false");
    gState = FINISHED;
}

void Fail(const string &in reason)
{
    if (gState == FINISHED)
        return;
    Finish();
    game.log("[RoR|CW2|NeoBridgeDrive] FAIL reason=" + reason);
    game.quitGame();
}

void main()
{
    InitializeStations();
    if (!ValidateRouteContract())
    {
        Fail("route-contract-invalid");
        return;
    }
    @gAppState = console.cVarFind("app_state");
    @gSimState = console.cVarFind("sim_state");
    if (@gAppState == null || @gSimState == null)
    {
        Fail("required-cvar-missing");
        return;
    }
    console.cVarSet("sim_deterministic_fixed_steps_per_frame", "40");
    console.cVarSet("sim_deterministic_sleeping_engine", "true");
    console.cVarSet("sim_no_collisions", "false");
    console.cVarSet("sim_no_self_collisions", "false");
    console.cVarSet("ui_hide_gui", "true");
    game.registerForEvent(SE_GENERIC_NEW_TRUCK);
    game.log(
        "[RoR|CW2|NeoBridgeDrive] START route_m=3076.132100441 "
        "waypoints=80 vehicle=b6b0UID-semi.truck batch=40 "
        "source_overlap_m=0 destination_overlap_m=0 "
        "collisions=on self_collisions=on "
        "traversal=destination-bidirectional");
}

void eventCallbackEx(
    scriptEvents event,
    int arg1,
    int arg2,
    int arg3,
    int arg4,
    string arg5,
    string arg6,
    string arg7,
    string arg8)
{
    if (event != SE_GENERIC_NEW_TRUCK)
        return;
    if (arg1 != gExpectedActorId)
    {
        Fail("unexpected-actor-id-" + arg1);
        return;
    }
    gActorSpawned = true;
}

bool SpawnActor()
{
    return game.pushMessage(
        MSG_SIM_SPAWN_ACTOR_REQUESTED,
        {
            {"filename", VEHICLE},
            {"instance_id", ACTOR_ID},
            {"free_position", true},
            {"enter", false},
            {"position", vector3(3780.970703f, 2.1f, 3993.104004f)},
            // The DAF's physical forward axis is -X. A 180 degree Y rotation
            // aligns it with the bridge's eastbound source tangent.
            {"rotation", quaternion(
                radian(3.141592654f),
                vector3(0.0f, 1.0f, 0.0f))}
        });
}

bool SpawnReverseActor()
{
    return game.pushMessage(
        MSG_SIM_SPAWN_ACTOR_REQUESTED,
        {
            {"filename", VEHICLE},
            {"instance_id", REVERSE_ACTOR_ID},
            {"free_position", true},
            {"enter", false},
            {"position", vector3(6887.0f, 2.2f, 4023.8f)},
            // With no Y rotation the DAF's -X physical forward axis points
            // west, from the preserved NeoQ2.0 lane onto the generated deck.
            {"rotation", quaternion(
                radian(0.0f),
                vector3(0.0f, 1.0f, 0.0f))}
        });
}

void HoldCamera(const vector3 &in position, float direction)
{
    const vector3 target = SamplePath(
        gClosestStation + direction * 26.0f);
    game.setCameraPosition(position + vector3(-30.0f, 15.0f, -24.0f));
    game.cameraLookAt(target + vector3(0.0f, 1.6f, 0.0f));
}

void UpdateControls(const vector3 &in position)
{
    const float targetStation = gClosestStation + LOOKAHEAD_M;
    vector3 target = SamplePath(targetStation);
    const vector3 tangent = PathTangent(targetStation);
    const float targetCrossTrack = TargetCrossTrack(targetStation);
    target.x += -tangent.z * targetCrossTrack;
    target.z += tangent.x * targetCrossTrack;
    const float desiredHeading = atan2(
        target.x - position.x,
        -(target.z - position.z));
    const float headingError = WrapAngle(
        gActor.getHeadingDirectionAngle() - desiredHeading);
    ApplySteer(Clamp(headingError * 0.88f, -0.28f, 0.28f));

    const float speed = gActor.getSpeed();
    float throttle = 0.20f;
    if (speed < 5.0f)
        throttle = 0.82f;
    else if (speed < 12.0f)
        throttle = 0.60f;
    else if (speed < 19.0f)
        throttle = 0.42f;
    else if (speed < 23.0f)
        throttle = 0.25f;
    else
        throttle = 0.06f;
    // Arrive at the independently authored destination mesh gently. This
    // avoids treating a high-speed collision impulse at its seam as evidence
    // about the generated bridge's alignment or collision continuity.
    if (gClosestStation > 2920.0f)
    {
        if (speed > 12.0f)
            throttle = 0.0f;
        else if (speed > 9.0f)
            throttle = 0.16f;
        else
            throttle = 0.45f;
    }
    gActor.setEventSimulatedValue(EV_TRUCK_ACCELERATE, throttle);
    gActor.setEventSimulatedValue(
        EV_TRUCK_BRAKE,
        (
            gClosestStation > 2920.0f && speed > 13.0f
            ? 0.28f
            : (speed > 25.0f ? 0.24f : 0.0f)
        ));
}

void UpdateReverseControls(const vector3 &in position)
{
    const float targetStation = gClosestStation - LOOKAHEAD_M;
    vector3 target = SamplePath(targetStation);
    const vector3 tangent = PathTangent(targetStation);
    target.x += -tangent.z * gReferenceCrossTrack;
    target.z += tangent.x * gReferenceCrossTrack;
    const float desiredHeading = atan2(
        target.x - position.x,
        -(target.z - position.z));
    const float headingError = WrapAngle(
        gActor.getHeadingDirectionAngle() - desiredHeading);
    ApplySteer(Clamp(headingError * 0.84f, -0.26f, 0.26f));

    const float speed = abs(gActor.getSpeed());
    float throttle = 0.08f;
    if (speed < 3.0f)
        throttle = 0.62f;
    else if (speed < 6.0f)
        throttle = 0.40f;
    else if (speed < 8.0f)
        throttle = 0.22f;
    gActor.setEventSimulatedValue(EV_TRUCK_ACCELERATE, throttle);
    gActor.setEventSimulatedValue(
        EV_TRUCK_BRAKE,
        speed > 10.0f ? 0.24f : 0.0f);
}

void RecordMotion(
    const vector3 &in position,
    float direction,
    bool monitorPath)
{
    if (gHasLastPosition)
    {
        gDistance += Distance2D(
            position.x,
            position.z,
            gLastPosition.x,
            gLastPosition.z);
    }
    gLastPosition = position;
    gHasLastPosition = true;

    const float targetCrossTrack = direction > 0.0f
        ? TargetCrossTrack(gClosestStation)
        : gReferenceCrossTrack;
    const float pathError = abs(
        gClosestCrossTrack - targetCrossTrack);
    const float verticalError = abs(
        (position.y - gClosestSurfaceY) - gReferenceHeight);
    if (monitorPath && pathError > gMaximumPathError)
        gMaximumPathError = pathError;
    if (verticalError > gMaximumVerticalError)
        gMaximumVerticalError = verticalError;
    const float regression = direction > 0.0f
        ? gPreviousProgress - gClosestStation
        : gClosestStation - gPreviousProgress;
    if (regression > gMaximumRegression)
        gMaximumRegression = regression;
    if (
        (direction > 0.0f && gClosestStation > gPreviousProgress) ||
        (direction < 0.0f && gClosestStation < gPreviousProgress)
    )
    {
        gPreviousProgress = gClosestStation;
    }
}

bool CheckProgress(float direction)
{
    const uint64 physicsSteps = game.getCompletedPhysicsSteps();
    if (
        (direction > 0.0f &&
            gClosestStation >=
                gProgressCheckpointStation + PROGRESS_WINDOW_M) ||
        (direction < 0.0f &&
            gClosestStation <=
                gProgressCheckpointStation - PROGRESS_WINDOW_M)
    )
    {
        gProgressCheckpointStation = gClosestStation;
        gProgressCheckpointStep = physicsSteps;
    }
    else if (
        gDrivingFrames > 300 &&
        physicsSteps > gProgressCheckpointStep + MAX_NO_PROGRESS_STEPS)
    {
        Fail(
            (direction > 0.0f
                ? "forward-progress-timeout-"
                : "reverse-progress-timeout-") +
            gClosestStation);
        return false;
    }
    return true;
}

bool CheckPhysicalBounds()
{
    if (gDrivingFrames > 300 &&
        gMaximumPathError > MAX_PATH_ERROR_M)
    {
        Fail("maximum-path-error-" + gMaximumPathError);
        return false;
    }
    if (gDrivingFrames > 300 &&
        gMaximumVerticalError > MAX_VERTICAL_ERROR_M)
    {
        Fail("maximum-vertical-error-" + gMaximumVerticalError);
        return false;
    }
    if (gMaximumRegression > MAX_REGRESSION_M)
    {
        Fail("route-regression-" + gMaximumRegression);
        return false;
    }
    return true;
}

void UpdateForward()
{
    const vector3 position = gActor.getPosition();
    FindClosestPath(position);
    HoldCamera(position, 1.0f);
    UpdateControls(position);
    RecordMotion(
        position,
        1.0f,
        gClosestStation < DESTINATION_LANE_SHIFT_START_M);
    if (!CheckProgress(1.0f))
        return;
    if (
        !gSourceSeam &&
        gClosestStation >= SOURCE_SEAM_STATION &&
        position.x >= SOURCE_SEAM_X_M)
    {
        gSourceSeam = true;
        game.log(
            "[RoR|CW2|NeoBridgeDrive] SEAM name=source station=" +
            gClosestStation + " x=" + position.x + " z=" + position.z);
    }
    if (!gMidpoint && gClosestStation >= MIDPOINT_STATION)
    {
        gMidpoint = true;
        game.log(
            "[RoR|CW2|NeoBridgeDrive] MIDPOINT station=" +
            gClosestStation + " x=" + position.x + " z=" + position.z);
    }
    if (
        !gDestinationSeam &&
        gClosestStation >= DESTINATION_SEAM_STATION)
    {
        gDestinationSeam = true;
        game.log(
            "[RoR|CW2|NeoBridgeDrive] SEAM name=destination station=" +
            gClosestStation + " x=" + position.x + " z=" + position.z);
    }

    if (!CheckPhysicalBounds())
        return;

    if (
        gDestinationSeam &&
        position.x >= PASS_DESTINATION_X_M)
    {
        if (!gSourceSeam || !gMidpoint || !gDestinationSeam)
        {
            Fail("route-marker-missing");
            return;
        }
        if (gDistance < 3050.0f || gDistance > 3400.0f)
        {
            Fail("distance-" + gDistance);
            return;
        }
        const float destinationLocalZ = position.z - 4018.0f;
        if (
            destinationLocalZ < DESTINATION_LANE_SAFE_MIN_LOCAL_Z_M ||
            destinationLocalZ > DESTINATION_LANE_SAFE_MAX_LOCAL_Z_M)
        {
            Fail("destination-lane-footprint-" + destinationLocalZ);
            return;
        }
        gForwardDestinationStation = gClosestStation;
        gForwardDestinationX = position.x;
        gForwardDestinationLocalZ = destinationLocalZ;
        ClearControls();
        gActor.setEventSimulatedValue(EV_TRUCK_BRAKE, 1.0f);
        gState = BRAKING_FOR_REVERSE;
    }
}

void UpdateBrakeForReverse()
{
    const vector3 position = gActor.getPosition();
    FindClosestPath(position);
    if (gHasLastPosition)
    {
        gDistance += Distance2D(
            position.x,
            position.z,
            gLastPosition.x,
            gLastPosition.z);
    }
    gLastPosition = position;
    ClearControls();
    gActor.setEventSimulatedValue(EV_TRUCK_BRAKE, 1.0f);
    HoldCamera(position, -1.0f);
    if (abs(gActor.getSpeed()) > 0.35f)
        return;

    gForwardDistance = gDistance;
    if (gForwardDistance < 3050.0f || gForwardDistance > 3450.0f)
    {
        Fail("forward-distance-" + gForwardDistance);
        return;
    }
    game.pushMessage(
        MSG_SIM_DELETE_ACTOR_REQUESTED,
        {{"instance_id", ACTOR_ID}});
    @gActor = null;
    @gEngine = null;
    gActorSpawned = false;
    gExpectedActorId = REVERSE_ACTOR_ID;
    gHasLastPosition = false;
    if (!SpawnReverseActor())
    {
        Fail("reverse-spawn-request-rejected");
        return;
    }
    gState = WAITING_FOR_REVERSE_ACTOR;
}

void ArmReverseActor()
{
    @gActor = game.getTruckByNum(REVERSE_ACTOR_ID);
    if (@gActor == null)
    {
        Fail("reverse-actor-not-addressable");
        return;
    }
    @gEngine = gActor.getEngine();
    if (@gEngine == null)
    {
        Fail("reverse-engine-missing");
        return;
    }
    gEngine.setAutoMode(SimGearboxMode::AUTO);
    gEngine.startEngine();
    if (gActor.getParkingBrake())
        gActor.parkingbrakeToggle();
    const vector3 position = gActor.getPosition();
    FindClosestPath(position);
    const float localZ = position.z - 4018.0f;
    if (
        gClosestStation < DESTINATION_SEAM_STATION + 17.0f ||
        gClosestStation > DESTINATION_SEAM_STATION + 20.1f ||
        localZ < DESTINATION_LANE_SAFE_MIN_LOCAL_Z_M ||
        localZ > DESTINATION_LANE_SAFE_MAX_LOCAL_Z_M
    )
    {
        Fail(
            "reverse-spawn-not-inside-neoq20-lane-" +
            gClosestStation + "-" + localZ);
        return;
    }
    gReferenceCrossTrack = gClosestCrossTrack;
    gReferenceHeight = position.y - gClosestSurfaceY;
    gPreviousProgress = gClosestStation;
    gProgressCheckpointStation = gClosestStation;
    gProgressCheckpointStep = game.getCompletedPhysicsSteps();
    gLastPosition = position;
    gHasLastPosition = true;
    gState = DRIVING_REVERSE;
    game.log(
        "[RoR|CW2|NeoBridgeDrive] REVERSE_ARMED actor=2026072903 "
        "direction=neoq20_to_neoq heading=" +
        gActor.getHeadingDirectionAngle() +
        " station=" + gClosestStation +
        " cross_track=" + gReferenceCrossTrack +
        " height=" + gReferenceHeight +
        " forward_distance_m=" + gForwardDistance);
}

void UpdateReverse()
{
    const vector3 position = gActor.getPosition();
    FindClosestPath(position);
    HoldCamera(position, -1.0f);
    UpdateReverseControls(position);
    RecordMotion(position, -1.0f, true);
    if (!CheckProgress(-1.0f))
        return;

    if (
        !gReverseDestinationSeam &&
        gClosestStation <= DESTINATION_SEAM_STATION)
    {
        gReverseDestinationLocalZ = position.z - 4018.0f;
        if (
            gReverseDestinationLocalZ
                < DESTINATION_LANE_SAFE_MIN_LOCAL_Z_M ||
            gReverseDestinationLocalZ
                > DESTINATION_LANE_SAFE_MAX_LOCAL_Z_M)
        {
            Fail(
                "reverse-destination-lane-footprint-" +
                gReverseDestinationLocalZ);
            return;
        }
        gReverseDestinationSeam = true;
        game.log(
            "[RoR|CW2|NeoBridgeDrive] REVERSE_DESTINATION_SEAM "
            "direction=neoq20_to_neoq target_station=3076.132100441 "
            "station=" + gClosestStation +
            " x=" + position.x +
            " z=" + position.z +
            " local_z=" + gReverseDestinationLocalZ);
    }
    if (!CheckPhysicalBounds())
        return;

    if (gClosestStation <= REVERSE_PASS_STATION)
    {
        if (!gReverseDestinationSeam)
        {
            Fail("reverse-destination-marker-missing");
            return;
        }
        const float reverseDistance = gDistance - gForwardDistance;
        if (reverseDistance < 45.0f || reverseDistance > 100.0f)
        {
            Fail("reverse-distance-" + reverseDistance);
            return;
        }
        if (gDistance < 3100.0f || gDistance > 3550.0f)
        {
            Fail("distance-" + gDistance);
            return;
        }
        const float finalSpeed = abs(gActor.getSpeed());
        const uint64 finalSteps = game.getCompletedPhysicsSteps();
        Finish();
        game.log(
            "[RoR|CW2|NeoBridgeDrive] PASS seams=3 traversals=2 "
            "destination_traversals=2 route_m=3076.132100441 "
            "station_m=" + gForwardDestinationStation +
            " reverse_station_m=" + gClosestStation +
            " destination_x_m=" + gForwardDestinationX +
            " destination_local_z_m=" + gForwardDestinationLocalZ +
            " reverse_destination_local_z_m=" +
                gReverseDestinationLocalZ +
            " distance_m=" + gDistance +
            " forward_distance_m=" + gForwardDistance +
            " reverse_distance_m=" + reverseDistance +
            " path_error_m=" + gMaximumPathError +
            " vertical_error_m=" + gMaximumVerticalError +
            " regression_m=" + gMaximumRegression +
            " speed_mps=" + finalSpeed +
            " physics_steps=" + finalSteps);
        game.quitGame();
    }
}

void frameStep(float dt)
{
    if (gState == FINISHED)
        return;

    if (gState == WAITING_FOR_TERRAIN)
    {
        if (gAppState.getInt() == APP_STATE_SIMULATION)
        {
            console.cVarSet("sim_state", "" + SIM_STATE_PAUSED);
            gState = WAITING_FOR_PAUSE;
        }
        return;
    }
    if (gState == WAITING_FOR_PAUSE)
    {
        if (gSimState.getInt() != SIM_STATE_PAUSED)
            return;
        if (!SpawnActor())
        {
            Fail("spawn-request-rejected");
            return;
        }
        gState = WAITING_FOR_ACTOR;
        return;
    }
    if (gState == WAITING_FOR_ACTOR)
    {
        if (!gActorSpawned)
            return;
        @gActor = game.getTruckByNum(ACTOR_ID);
        if (@gActor == null)
        {
            Fail("actor-not-addressable");
            return;
        }
        @gEngine = gActor.getEngine();
        if (@gEngine == null)
        {
            Fail("engine-missing");
            return;
        }
        gEngine.setAutoMode(SimGearboxMode::AUTO);
        gEngine.startEngine();
        if (gActor.getParkingBrake())
            gActor.parkingbrakeToggle();
        const vector3 position = gActor.getPosition();
        FindClosestPath(position);
        if (gClosestStation < 0.0f || gClosestStation > 4.0f)
        {
            Fail("spawn-not-inside-neoq-road-" + gClosestStation);
            return;
        }
        gReferenceCrossTrack = gClosestCrossTrack;
        gReferenceHeight = position.y - gClosestSurfaceY;
        gPreviousProgress = gClosestStation;
        gProgressCheckpointStation = gClosestStation;
        gProgressCheckpointStep = game.getCompletedPhysicsSteps();
        game.pushMessage(MSG_SIM_UNPAUSE_REQUESTED, {});
        gState = DRIVING_FORWARD;
        game.log(
            "[RoR|CW2|NeoBridgeDrive] ARMED actor=2026072902 "
            "heading=" + gActor.getHeadingDirectionAngle() +
            " station=" + gClosestStation +
            " cross_track=" + gReferenceCrossTrack +
            " height=" + gReferenceHeight);
        return;
    }
    if (gState == WAITING_FOR_REVERSE_ACTOR)
    {
        if (gActorSpawned)
            ArmReverseActor();
        return;
    }
    if (
        gState == DRIVING_FORWARD ||
        gState == BRAKING_FOR_REVERSE ||
        gState == DRIVING_REVERSE)
    {
        gDrivingFrames++;
        if (game.getCompletedPhysicsSteps() > MAX_PHYSICS_STEPS)
        {
            Fail("physics-step-timeout");
            return;
        }
        if (gDrivingFrames % 250 == 0)
        {
            const vector3 position = gActor.getPosition();
            game.log(
                "[RoR|CW2|NeoBridgeDrive] SAMPLE frame=" +
                gDrivingFrames +
                " state=" + gState +
                " station=" + gClosestStation +
                " x=" + position.x +
                " y=" + position.y +
                " z=" + position.z +
                " speed=" + gActor.getSpeed());
        }
        if (gState == DRIVING_FORWARD)
            UpdateForward();
        else if (gState == BRAKING_FOR_REVERSE)
            UpdateBrakeForReverse();
        else
            UpdateReverse();
    }
}
