/// \title CityWorld Neo-to-NeoQ2.0 full bridge drive gate
/// \brief Drives the packaged DAF across both authenticated city-road seams.

const int APP_STATE_SIMULATION = 2;
const int SIM_STATE_PAUSED = 2;
const int64 ACTOR_ID = 2026072902;
const uint64 MAX_PHYSICS_STEPS = 650000;
const uint64 MAX_NO_PROGRESS_STEPS = 80000;
const string VEHICLE = "b6b0UID-semi.truck";

const float ROUTE_LENGTH_M = 3086.132100441f;
const float SOURCE_SEAM_STATION = 10.0f;
const float MIDPOINT_STATION = 1543.066050221f;
const float DESTINATION_SEAM_STATION = ROUTE_LENGTH_M;
const float PASS_DESTINATION_X_M = 6877.0f;
const float LOOKAHEAD_M = 30.0f;
const float MAX_PATH_ERROR_M = 2.5f;
const float MAX_VERTICAL_ERROR_M = 4.0f;
const float MAX_REGRESSION_M = 8.0f;
const float PROGRESS_WINDOW_M = 5.0f;
const float DESTINATION_LANE_SHIFT_START_M = 2200.0f;
const float DESTINATION_LANE_SHIFT_END_M = 2600.0f;
const float DESTINATION_LANE_CROSS_TRACK_M = 5.8f;
const float DESTINATION_LANE_SAFE_MIN_LOCAL_Z_M = 1.95f;
const float DESTINATION_LANE_SAFE_MAX_LOCAL_Z_M = 6.30f;

// These are the exact v1 overlay route points generated by
// tools/cityworld_neoq_intercity_bridge.py with surface_offset_m=0.08. Point
// zero is 10 m inside NeoQueretaro's east distributor, point one is its mesh
// seam, and point 80 ends flush at NeoQ2.0's west distributor seam. The gate
// then drives another 10 m using only the independently authored destination
// collision, inside its positive-local-Z carriageway.
array<vector3> gPath = {
    vector3(3780.970703000f, 0.100000000f, 3993.104004000f),
    vector3(3790.970703000f, 0.100000000f, 3993.104004000f),
    vector3(3830.970497719f, 0.180050286f, 3993.221193040f),
    vector3(3870.969932807f, 1.430199386f, 3993.432756338f),
    vector3(3910.969157867f, 4.180444662f, 3993.681695191f),
    vector3(3950.968244180f, 6.930783474f, 3993.952208108f),
    vector3(3990.967229427f, 8.181213185f, 3994.237176793f),
    vector3(4030.966136955f, 8.181731155f, 3994.532669098f),
    vector3(4070.964987513f, 8.182334747f, 3994.836240814f),
    vector3(4110.963784330f, 8.183021323f, 3995.146249174f),
    vector3(4150.962544713f, 8.183788242f, 3995.461526847f),
    vector3(4190.961264746f, 8.184632869f, 3995.781208483f),
    vector3(4230.959956575f, 8.185552563f, 3996.104631318f),
    vector3(4270.958624091f, 8.186544686f, 3996.431273928f),
    vector3(4310.957269383f, 8.187606600f, 3996.760717005f),
    vector3(4350.955889681f, 8.188735667f, 3997.092617021f),
    vector3(4390.954495804f, 8.189929248f, 3997.426688168f),
    vector3(4430.953084800f, 8.191184705f, 3997.762689158f),
    vector3(4470.951658578f, 8.192499398f, 3998.100413913f),
    vector3(4510.950219671f, 8.193870691f, 3998.439684475f),
    vector3(4550.948770367f, 8.195295944f, 3998.780345642f),
    vector3(4590.947308326f, 8.196772518f, 3999.122260803f),
    vector3(4630.945837314f, 8.198297777f, 3999.465308791f),
    vector3(4670.944356948f, 8.199869080f, 3999.809381228f),
    vector3(4710.942869586f, 8.201483790f, 4000.154380524f),
    vector3(4750.941375203f, 8.203139268f, 4000.500218153f),
    vector3(4790.939874198f, 8.204832875f, 4000.846813305f),
    vector3(4830.938365650f, 8.206561974f, 4001.194091728f),
    vector3(4870.936852832f, 8.208323926f, 4001.541984822f),
    vector3(4910.935335775f, 8.210116093f, 4001.890428764f),
    vector3(4950.933813909f, 8.211935835f, 4002.239363845f),
    vector3(4990.932287748f, 8.213780515f, 4002.588733891f),
    vector3(5030.930758753f, 8.215647494f, 4002.938485745f),
    vector3(5070.929227410f, 8.217534134f, 4003.288568797f),
    vector3(5110.927692440f, 8.219437796f, 4003.638934576f),
    vector3(5150.926156224f, 8.221355841f, 4003.989536438f),
    vector3(5190.924617836f, 8.223285633f, 4004.340329174f),
    vector3(5230.923078603f, 8.225224531f, 4004.691268761f),
    vector3(5270.921538133f, 8.227169897f, 4005.042312042f),
    vector3(5310.919997278f, 8.229119094f, 4005.393416489f),
    vector3(5350.918456274f, 8.231069482f, 4005.744539931f),
    vector3(5390.916915470f, 8.233018424f, 4006.095640309f),
    vector3(5430.915375117f, 8.234963280f, 4006.446675429f),
    vector3(5470.913835898f, 8.236901413f, 4006.797602711f),
    vector3(5510.912297654f, 8.238830184f, 4007.148378929f),
    vector3(5550.910761684f, 8.240746954f, 4007.498959959f),
    vector3(5590.909227012f, 8.242649085f, 4007.849300463f),
    vector3(5630.907695993f, 8.244533939f, 4008.199353638f),
    vector3(5670.906167337f, 8.246398877f, 4008.549070820f),
    vector3(5710.904642007f, 8.248241261f, 4008.898401176f),
    vector3(5750.903120333f, 8.250058452f, 4009.247291269f),
    vector3(5790.901602991f, 8.251847812f, 4009.595684608f),
    vector3(5830.900091037f, 8.253606702f, 4009.943521126f),
    vector3(5870.898583607f, 8.255332484f, 4010.290736563f),
    vector3(5910.897082849f, 8.257022520f, 4010.637261800f),
    vector3(5950.895589021f, 8.258674171f, 4010.983022007f),
    vector3(5990.894101377f, 8.260284799f, 4011.327935669f),
    vector3(6030.892622713f, 8.261851765f, 4011.671913473f),
    vector3(6070.891151565f, 8.263372431f, 4012.014856831f),
    vector3(6110.889691039f, 8.264844158f, 4012.356656255f),
    vector3(6150.888241751f, 8.266264309f, 4012.697189181f),
    vector3(6190.886805082f, 8.267630243f, 4013.036317384f),
    vector3(6230.885379536f, 8.268939324f, 4013.373883625f),
    vector3(6270.883969861f, 8.270188913f, 4013.709707504f),
    vector3(6310.882578296f, 8.271376371f, 4014.043579884f),
    vector3(6350.881202828f, 8.272499059f, 4014.375255629f),
    vector3(6390.879849590f, 8.273554340f, 4014.704443956f),
    vector3(6430.878515962f, 8.274539575f, 4015.030794906f),
    vector3(6470.877213354f, 8.275452125f, 4015.353880680f),
    vector3(6510.875936122f, 8.276289353f, 4015.673168083f),
    vector3(6550.874699569f, 8.277048619f, 4015.987977919f),
    vector3(6590.873500316f, 8.277727285f, 4016.297420803f),
    vector3(6630.872353119f, 8.278322713f, 4016.600292610f),
    vector3(6667.003473573f, 8.278786815f, 4016.866827207f),
    vector3(6670.871271105f, 8.265032698f, 4016.894890913f),
    vector3(6710.870263072f, 6.804897187f, 4017.178666295f),
    vector3(6750.869361284f, 3.989716756f, 4017.447479434f),
    vector3(6790.868601538f, 1.319488767f, 4017.693725326f),
    vector3(6827.000205281f, 0.279949714f, 4017.882810960f),
    vector3(6830.868064918f, 0.277859503f, 4017.900037554f),
    vector3(6867.000000000f, 0.200000000f, 4018.000000000f)
};

array<float> gStation;

enum RuntimeState
{
    WAITING_FOR_TERRAIN = 0,
    WAITING_FOR_PAUSE,
    WAITING_FOR_ACTOR,
    DRIVING,
    FINISHED
}

RuntimeState gState = WAITING_FOR_TERRAIN;
BeamClass@ gActor;
CVarClass@ gAppState;
CVarClass@ gSimState;
bool gActorSpawned = false;
bool gSourceSeam = false;
bool gMidpoint = false;
bool gDestinationSeam = false;
bool gHasLastPosition = false;
uint gDrivingFrames = 0;
float gDistance = 0.0f;
float gClosestStation = 0.0f;
float gClosestCrossTrack = 0.0f;
float gClosestSurfaceY = 0.1f;
float gReferenceCrossTrack = 0.0f;
float gReferenceHeight = 0.0f;
float gMaximumPathError = 0.0f;
float gMaximumVerticalError = 0.0f;
float gMaximumRegression = 0.0f;
float gPreviousProgress = 0.0f;
float gProgressCheckpointStation = 0.0f;
uint64 gProgressCheckpointStep = 0;
vector3 gLastPosition;

float Clamp(float value, float minimum, float maximum)
{
    if (value < minimum)
        return minimum;
    if (value > maximum)
        return maximum;
    return value;
}

float Distance2D(
    float firstX,
    float firstZ,
    float secondX,
    float secondZ)
{
    const float dx = firstX - secondX;
    const float dz = firstZ - secondZ;
    return sqrt(dx * dx + dz * dz);
}

float WrapAngle(float value)
{
    while (value > 3.141592654f)
        value -= 6.283185307f;
    while (value < -3.141592654f)
        value += 6.283185307f;
    return value;
}

void InitializeStations()
{
    gStation.resize(81);
    gStation[0] = 0.0f;
    gStation[1] = 10.0f;
    for (uint index = 2; index <= 72; index++)
        gStation[index] = 50.0f + 40.0f * float(index - 2);
    gStation[73] = 2886.132100441f;
    gStation[74] = 2890.0f;
    gStation[75] = 2930.0f;
    gStation[76] = 2970.0f;
    gStation[77] = 3010.0f;
    gStation[78] = 3046.132100441f;
    gStation[79] = 3050.0f;
    gStation[80] = DESTINATION_SEAM_STATION;
}

bool ValidateRouteContract()
{
    if (gPath.length() != 81 || gStation.length() != gPath.length())
        return false;
    for (uint index = 0; index + 1 < gStation.length(); index++)
    {
        if (gStation[index + 1] <= gStation[index])
            return false;
    }
    if (
        Distance2D(gPath[0].x, gPath[0].z, 3780.970703f, 3993.104004f)
            > 0.01f ||
        Distance2D(gPath[1].x, gPath[1].z, 3790.970703f, 3993.104004f)
            > 0.01f ||
        Distance2D(gPath[80].x, gPath[80].z, 6867.0f, 4018.0f)
            > 0.01f)
    {
        return false;
    }
    return (
        abs(gStation[1] - SOURCE_SEAM_STATION) <= 0.01f &&
        abs(gStation[80] - DESTINATION_SEAM_STATION) <= 0.01f &&
        abs(gStation[80] - ROUTE_LENGTH_M) <= 0.01f);
}

void FindClosestPath(const vector3 &in position)
{
    float bestSquared = 1000000000.0f;
    for (uint index = 0; index + 1 < gPath.length(); index++)
    {
        const float dx = gPath[index + 1].x - gPath[index].x;
        const float dz = gPath[index + 1].z - gPath[index].z;
        const float lengthSquared = dx * dx + dz * dz;
        if (lengthSquared <= 0.000001f)
            continue;
        const float fraction = Clamp(
            (
                (position.x - gPath[index].x) * dx +
                (position.z - gPath[index].z) * dz
            ) / lengthSquared,
            0.0f,
            1.0f);
        const float projectedX = gPath[index].x + fraction * dx;
        const float projectedZ = gPath[index].z + fraction * dz;
        const float offsetX = position.x - projectedX;
        const float offsetZ = position.z - projectedZ;
        const float squared = offsetX * offsetX + offsetZ * offsetZ;
        if (squared >= bestSquared)
            continue;
        bestSquared = squared;
        const float length = sqrt(lengthSquared);
        gClosestStation =
            gStation[index] +
            fraction * (gStation[index + 1] - gStation[index]);
        gClosestCrossTrack = (dx * offsetZ - dz * offsetX) / length;
        gClosestSurfaceY =
            gPath[index].y +
            fraction * (gPath[index + 1].y - gPath[index].y);
    }
}

vector3 SamplePath(float station)
{
    if (station <= gStation[0])
        return gPath[0];
    const uint last = gStation.length() - 1;
    if (station >= gStation[last])
    {
        const vector3 delta = gPath[last] - gPath[last - 1];
        const float segmentLength =
            gStation[last] - gStation[last - 1];
        return (
            gPath[last] +
            delta * ((station - gStation[last]) / segmentLength)
        );
    }
    for (uint index = 0; index < last; index++)
    {
        if (station > gStation[index + 1])
            continue;
        const float fraction =
            (station - gStation[index]) /
            (gStation[index + 1] - gStation[index]);
        return gPath[index] + (gPath[index + 1] - gPath[index]) * fraction;
    }
    return gPath[last];
}

vector3 PathTangent(float station)
{
    const vector3 before = SamplePath(station - 1.0f);
    const vector3 after = SamplePath(station + 1.0f);
    vector3 tangent(after.x - before.x, 0.0f, after.z - before.z);
    const float length = sqrt(tangent.x * tangent.x + tangent.z * tangent.z);
    if (length > 0.000001f)
    {
        tangent.x /= length;
        tangent.z /= length;
    }
    return tangent;
}

float TargetCrossTrack(float station)
{
    const float linear = Clamp(
        (
            station - DESTINATION_LANE_SHIFT_START_M
        ) / (
            DESTINATION_LANE_SHIFT_END_M -
            DESTINATION_LANE_SHIFT_START_M
        ),
        0.0f,
        1.0f);
    const float eased = linear * linear * (3.0f - 2.0f * linear);
    return (
        gReferenceCrossTrack +
        eased * (
            DESTINATION_LANE_CROSS_TRACK_M -
            gReferenceCrossTrack
        ));
}

void ApplySteer(float steer)
{
    if (steer >= 0.0f)
    {
        gActor.setEventSimulatedValue(EV_TRUCK_STEER_LEFT, steer);
        gActor.setEventSimulatedValue(EV_TRUCK_STEER_RIGHT, 0.0f);
    }
    else
    {
        gActor.setEventSimulatedValue(EV_TRUCK_STEER_LEFT, 0.0f);
        gActor.setEventSimulatedValue(EV_TRUCK_STEER_RIGHT, -steer);
    }
}

void ClearControls()
{
    if (@gActor != null)
        gActor.clearEventSimulatedValues();
}

void Finish()
{
    ClearControls();
    console.cVarSet("sim_deterministic_fixed_steps_per_frame", "0");
    console.cVarSet("ui_hide_gui", "false");
    gState = FINISHED;
}

void Fail(const string &in reason)
{
    if (gState == FINISHED)
        return;
    Finish();
    game.log("[RoR|CW2|NeoBridgeDrive] FAIL reason=" + reason);
    game.quitGame();
}

void main()
{
    InitializeStations();
    if (!ValidateRouteContract())
    {
        Fail("route-contract-invalid");
        return;
    }
    @gAppState = console.cVarFind("app_state");
    @gSimState = console.cVarFind("sim_state");
    if (@gAppState == null || @gSimState == null)
    {
        Fail("required-cvar-missing");
        return;
    }
    console.cVarSet("sim_deterministic_fixed_steps_per_frame", "40");
    console.cVarSet("sim_deterministic_sleeping_engine", "true");
    console.cVarSet("sim_no_collisions", "false");
    console.cVarSet("sim_no_self_collisions", "false");
    console.cVarSet("ui_hide_gui", "true");
    game.registerForEvent(SE_GENERIC_NEW_TRUCK);
    game.log(
        "[RoR|CW2|NeoBridgeDrive] START route_m=3086.132100441 "
        "waypoints=81 vehicle=b6b0UID-semi.truck batch=40 "
        "destination_overlap_m=0");
}

void eventCallbackEx(
    scriptEvents event,
    int arg1,
    int arg2,
    int arg3,
    int arg4,
    string arg5,
    string arg6,
    string arg7,
    string arg8)
{
    if (event != SE_GENERIC_NEW_TRUCK)
        return;
    if (arg1 != ACTOR_ID)
    {
        Fail("unexpected-actor-id-" + arg1);
        return;
    }
    gActorSpawned = true;
}

bool SpawnActor()
{
    return game.pushMessage(
        MSG_SIM_SPAWN_ACTOR_REQUESTED,
        {
            {"filename", VEHICLE},
            {"instance_id", ACTOR_ID},
            {"free_position", true},
            {"enter", false},
            {"position", vector3(3780.970703f, 2.1f, 3993.104004f)},
            // The DAF's physical forward axis is -X. A 180 degree Y rotation
            // aligns it with the bridge's eastbound source tangent.
            {"rotation", quaternion(
                radian(3.141592654f),
                vector3(0.0f, 1.0f, 0.0f))}
        });
}

void HoldCamera(const vector3 &in position)
{
    const vector3 target = SamplePath(gClosestStation + 26.0f);
    game.setCameraPosition(position + vector3(-30.0f, 15.0f, -24.0f));
    game.cameraLookAt(target + vector3(0.0f, 1.6f, 0.0f));
}

void UpdateControls(const vector3 &in position)
{
    const float targetStation = gClosestStation + LOOKAHEAD_M;
    vector3 target = SamplePath(targetStation);
    const vector3 tangent = PathTangent(targetStation);
    const float targetCrossTrack = TargetCrossTrack(targetStation);
    target.x += -tangent.z * targetCrossTrack;
    target.z += tangent.x * targetCrossTrack;
    const float desiredHeading = atan2(
        target.x - position.x,
        -(target.z - position.z));
    const float headingError = WrapAngle(
        gActor.getHeadingDirectionAngle() - desiredHeading);
    ApplySteer(Clamp(headingError * 0.88f, -0.28f, 0.28f));

    const float speed = gActor.getSpeed();
    float throttle = 0.20f;
    if (speed < 5.0f)
        throttle = 0.82f;
    else if (speed < 12.0f)
        throttle = 0.60f;
    else if (speed < 19.0f)
        throttle = 0.42f;
    else if (speed < 23.0f)
        throttle = 0.25f;
    else
        throttle = 0.06f;
    // Arrive at the independently authored destination mesh gently. This
    // avoids treating a high-speed collision impulse at its seam as evidence
    // about the generated bridge's alignment or collision continuity.
    if (gClosestStation > 2920.0f)
    {
        if (speed > 12.0f)
            throttle = 0.0f;
        else if (speed > 9.0f)
            throttle = 0.16f;
        else
            throttle = 0.45f;
    }
    gActor.setEventSimulatedValue(EV_TRUCK_ACCELERATE, throttle);
    gActor.setEventSimulatedValue(
        EV_TRUCK_BRAKE,
        (
            gClosestStation > 2920.0f && speed > 13.0f
            ? 0.28f
            : (speed > 25.0f ? 0.24f : 0.0f)
        ));
}

void UpdateTraversal()
{
    const vector3 position = gActor.getPosition();
    FindClosestPath(position);
    HoldCamera(position);
    UpdateControls(position);

    if (gHasLastPosition)
    {
        gDistance += Distance2D(
            position.x,
            position.z,
            gLastPosition.x,
            gLastPosition.z);
    }
    gLastPosition = position;
    gHasLastPosition = true;

    const float pathError = abs(
        gClosestCrossTrack - TargetCrossTrack(gClosestStation));
    const float verticalError = abs(
        (position.y - gClosestSurfaceY) - gReferenceHeight);
    if (
        gClosestStation < DESTINATION_LANE_SHIFT_START_M &&
        pathError > gMaximumPathError)
        gMaximumPathError = pathError;
    if (verticalError > gMaximumVerticalError)
        gMaximumVerticalError = verticalError;
    const float regression = gPreviousProgress - gClosestStation;
    if (regression > gMaximumRegression)
        gMaximumRegression = regression;
    if (gClosestStation > gPreviousProgress)
        gPreviousProgress = gClosestStation;

    const uint64 physicsSteps = game.getCompletedPhysicsSteps();
    if (
        gClosestStation >=
            gProgressCheckpointStation + PROGRESS_WINDOW_M)
    {
        gProgressCheckpointStation = gClosestStation;
        gProgressCheckpointStep = physicsSteps;
    }
    else if (
        gDrivingFrames > 300 &&
        physicsSteps > gProgressCheckpointStep + MAX_NO_PROGRESS_STEPS)
    {
        Fail("forward-progress-timeout-" + gClosestStation);
        return;
    }

    if (!gSourceSeam && gClosestStation >= SOURCE_SEAM_STATION)
    {
        gSourceSeam = true;
        game.log(
            "[RoR|CW2|NeoBridgeDrive] SEAM name=source station=" +
            gClosestStation + " x=" + position.x + " z=" + position.z);
    }
    if (!gMidpoint && gClosestStation >= MIDPOINT_STATION)
    {
        gMidpoint = true;
        game.log(
            "[RoR|CW2|NeoBridgeDrive] MIDPOINT station=" +
            gClosestStation + " x=" + position.x + " z=" + position.z);
    }
    if (
        !gDestinationSeam &&
        gClosestStation >= DESTINATION_SEAM_STATION)
    {
        gDestinationSeam = true;
        game.log(
            "[RoR|CW2|NeoBridgeDrive] SEAM name=destination station=" +
            gClosestStation + " x=" + position.x + " z=" + position.z);
    }

    if (
        gDrivingFrames > 300 &&
        gClosestStation < DESTINATION_LANE_SHIFT_START_M &&
        pathError > MAX_PATH_ERROR_M)
    {
        Fail("path-error-" + pathError);
        return;
    }
    if (gDrivingFrames > 300 && verticalError > MAX_VERTICAL_ERROR_M)
    {
        Fail("vertical-error-" + verticalError);
        return;
    }
    if (gMaximumRegression > MAX_REGRESSION_M)
    {
        Fail("route-regression-" + gMaximumRegression);
        return;
    }

    if (
        gDestinationSeam &&
        position.x >= PASS_DESTINATION_X_M)
    {
        if (!gSourceSeam || !gMidpoint || !gDestinationSeam)
        {
            Fail("route-marker-missing");
            return;
        }
        if (gMaximumPathError > MAX_PATH_ERROR_M)
        {
            Fail("maximum-path-error-" + gMaximumPathError);
            return;
        }
        if (gMaximumVerticalError > MAX_VERTICAL_ERROR_M)
        {
            Fail("maximum-vertical-error-" + gMaximumVerticalError);
            return;
        }
        if (gDistance < 3050.0f || gDistance > 3400.0f)
        {
            Fail("distance-" + gDistance);
            return;
        }
        const float destinationLocalZ = position.z - 4018.0f;
        if (
            destinationLocalZ < DESTINATION_LANE_SAFE_MIN_LOCAL_Z_M ||
            destinationLocalZ > DESTINATION_LANE_SAFE_MAX_LOCAL_Z_M)
        {
            Fail("destination-lane-footprint-" + destinationLocalZ);
            return;
        }
        const float finalSpeed = gActor.getSpeed();
        const uint64 finalSteps = game.getCompletedPhysicsSteps();
        Finish();
        game.log(
            "[RoR|CW2|NeoBridgeDrive] PASS seams=2 "
            "route_m=3086.132100441 station_m=" + gClosestStation +
            " destination_x_m=" + position.x +
            " destination_local_z_m=" + destinationLocalZ +
            " distance_m=" + gDistance +
            " path_error_m=" + gMaximumPathError +
            " vertical_error_m=" + gMaximumVerticalError +
            " regression_m=" + gMaximumRegression +
            " speed_mps=" + finalSpeed +
            " physics_steps=" + finalSteps);
        game.quitGame();
    }
}

void frameStep(float dt)
{
    if (gState == FINISHED)
        return;

    if (gState == WAITING_FOR_TERRAIN)
    {
        if (gAppState.getInt() == APP_STATE_SIMULATION)
        {
            console.cVarSet("sim_state", "" + SIM_STATE_PAUSED);
            gState = WAITING_FOR_PAUSE;
        }
        return;
    }
    if (gState == WAITING_FOR_PAUSE)
    {
        if (gSimState.getInt() != SIM_STATE_PAUSED)
            return;
        if (!SpawnActor())
        {
            Fail("spawn-request-rejected");
            return;
        }
        gState = WAITING_FOR_ACTOR;
        return;
    }
    if (gState == WAITING_FOR_ACTOR)
    {
        if (!gActorSpawned)
            return;
        @gActor = game.getTruckByNum(ACTOR_ID);
        if (@gActor == null)
        {
            Fail("actor-not-addressable");
            return;
        }
        EngineClass@ engine = gActor.getEngine();
        if (@engine == null)
        {
            Fail("engine-missing");
            return;
        }
        engine.setAutoMode(SimGearboxMode::AUTO);
        engine.startEngine();
        if (gActor.getParkingBrake())
            gActor.parkingbrakeToggle();
        const vector3 position = gActor.getPosition();
        FindClosestPath(position);
        if (gClosestStation < 0.0f || gClosestStation > 4.0f)
        {
            Fail("spawn-not-inside-neoq-road-" + gClosestStation);
            return;
        }
        gReferenceCrossTrack = gClosestCrossTrack;
        gReferenceHeight = position.y - gClosestSurfaceY;
        gPreviousProgress = gClosestStation;
        gProgressCheckpointStation = gClosestStation;
        gProgressCheckpointStep = game.getCompletedPhysicsSteps();
        game.pushMessage(MSG_SIM_UNPAUSE_REQUESTED, {});
        gState = DRIVING;
        game.log(
            "[RoR|CW2|NeoBridgeDrive] ARMED actor=2026072902 "
            "heading=" + gActor.getHeadingDirectionAngle() +
            " station=" + gClosestStation +
            " cross_track=" + gReferenceCrossTrack +
            " height=" + gReferenceHeight);
        return;
    }
    if (gState == DRIVING)
    {
        gDrivingFrames++;
        if (game.getCompletedPhysicsSteps() > MAX_PHYSICS_STEPS)
        {
            Fail("physics-step-timeout");
            return;
        }
        if (gDrivingFrames % 250 == 0)
        {
            const vector3 position = gActor.getPosition();
            game.log(
                "[RoR|CW2|NeoBridgeDrive] SAMPLE frame=" +
                gDrivingFrames +
                " station=" + gClosestStation +
                " x=" + position.x +
                " y=" + position.y +
                " z=" + position.z +
                " speed=" + gActor.getSpeed());
        }
        UpdateTraversal();
    }
}
