# CMake generated Testfile for 
# Source directory: /Users/beshoyhanna/Development/rigs-of-rods/tests
# Build directory: /Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(render_display_metrics "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_render_display_metrics_tests")
set_tests_properties(render_display_metrics PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;576;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(sky_mode_availability "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_sky_mode_availability_tests")
set_tests_properties(sky_mode_availability PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;581;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(beam_axial_response "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_beam_axial_response_tests")
set_tests_properties(beam_axial_response PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;586;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(beam_rest_length_scale "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_beam_rest_length_scale_tests")
set_tests_properties(beam_rest_length_scale PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;591;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_counter_noise "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_deterministic_counter_noise_tests")
set_tests_properties(deterministic_counter_noise PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;596;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_fixed_step_cadence "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_deterministic_fixed_step_cadence_tests")
set_tests_properties(deterministic_fixed_step_cadence PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;601;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_scenario_schedule "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_deterministic_scenario_schedule_tests")
set_tests_properties(deterministic_scenario_schedule PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;606;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_contact_order "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_deterministic_contact_order_tests")
set_tests_properties(deterministic_contact_order PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;611;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_state_digest "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_deterministic_state_digest_tests")
set_tests_properties(deterministic_state_digest PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;616;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_state_trace "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_deterministic_state_trace_tests")
set_tests_properties(deterministic_state_trace PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;621;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_input_trace "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_deterministic_input_trace_tests")
set_tests_properties(deterministic_input_trace PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;626;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_input_trace_runtime "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_deterministic_input_trace_runtime_tests")
set_tests_properties(deterministic_input_trace_runtime PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;631;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_vehicle_input "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_deterministic_vehicle_input_tests")
set_tests_properties(deterministic_vehicle_input PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;636;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(calibrated_beam_material "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_calibrated_beam_material_tests")
set_tests_properties(calibrated_beam_material PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;641;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(calibrated_beam_material_adapter "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_calibrated_beam_material_adapter_tests")
set_tests_properties(calibrated_beam_material_adapter PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;646;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(calibrated_beam_step_sensitivity "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_calibrated_beam_step_sensitivity_tests")
set_tests_properties(calibrated_beam_step_sensitivity PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;651;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(calibrated_beam_mesh_refinement "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_calibrated_beam_mesh_refinement_tests")
set_tests_properties(calibrated_beam_mesh_refinement PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;656;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(calibrated_beam_savegame "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_calibrated_beam_savegame_tests")
set_tests_properties(calibrated_beam_savegame PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;661;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(calibrated_beam_savegame_json "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_calibrated_beam_savegame_json_tests")
set_tests_properties(calibrated_beam_savegame_json PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;667;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(rigdef_calibrated_beam_material "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_rigdef_calibrated_beam_material_tests")
set_tests_properties(rigdef_calibrated_beam_material PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;673;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(rigdef_calibrated_beam_material_roundtrip_integration "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/RoR" "--internal-rigdef-calibrated-material-roundtrip" "/Users/beshoyhanna/Development/rigs-of-rods/tests/fixtures/rigdef/calibrated_beam_material_roundtrip.truck")
set_tests_properties(rigdef_calibrated_beam_material_roundtrip_integration PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;679;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(hydro_actuator_response "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_hydro_actuator_response_tests")
set_tests_properties(hydro_actuator_response PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;688;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(shader_compatibility_policy "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_shader_compatibility_policy_tests")
set_tests_properties(shader_compatibility_policy PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;693;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(beamng_package_manifest "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_beamng_package_manifest_tests")
set_tests_properties(beamng_package_manifest PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;698;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(beamng_material_inventory "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_beamng_material_inventory_tests")
set_tests_properties(beamng_material_inventory PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;703;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(beamng_zip_archive_index "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_beamng_zip_archive_index_tests")
set_tests_properties(beamng_zip_archive_index PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;708;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(beamng_zip_index_help "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_beamng_zip_index" "--help")
set_tests_properties(beamng_zip_index_help PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;713;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(beamng_formulacoupe_opt_in "/opt/homebrew/bin/cmake" "-DROR_BEAMNG_ZIP_INDEX_TOOL=/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_beamng_zip_index" "-P" "/Users/beshoyhanna/Development/rigs-of-rods/tests/resources/FormulaCoupeOptIn.cmake")
set_tests_properties(beamng_formulacoupe_opt_in PROPERTIES  SKIP_REGULAR_EXPRESSION "SKIP: FormulaCOUPE fixture is not explicitly supplied" _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;718;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(jbeam_expression_evaluator "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_jbeam_expression_evaluator_tests")
set_tests_properties(jbeam_expression_evaluator PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;733;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(jbeam_syntax "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_jbeam_syntax_tests")
set_tests_properties(jbeam_syntax PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;738;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(jbeam_coordinate_transform "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_jbeam_coordinate_transform_tests")
set_tests_properties(jbeam_coordinate_transform PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;743;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(jbeam_advanced_structure_ir "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_jbeam_advanced_structure_ir_tests")
set_tests_properties(jbeam_advanced_structure_ir PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;748;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(jbeam_part_resolver "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_jbeam_part_resolver_tests")
set_tests_properties(jbeam_part_resolver PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;753;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(jbeam_pressure_wheel_ir "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_jbeam_pressure_wheel_ir_tests")
set_tests_properties(jbeam_pressure_wheel_ir PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;758;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(jbeam_structural_ir "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_jbeam_structural_ir_tests")
set_tests_properties(jbeam_structural_ir PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;763;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(jbeam_to_rigdef "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_jbeam_to_rigdef_tests")
set_tests_properties(jbeam_to_rigdef PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;768;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(apple_executable_path "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_apple_executable_path_tests")
set_tests_properties(apple_executable_path PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;774;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(macos_user_directory_layout "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_macos_user_directory_layout_tests")
set_tests_properties(macos_user_directory_layout PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;778;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(macos_controller_contract "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_macos_controller_contract_tests")
set_tests_properties(macos_controller_contract PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;783;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(macos_input_bridge "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_macos_input_bridge_tests")
set_tests_properties(macos_input_bridge PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;787;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(macos_openal_smoke "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/r0-crossplatform-graph-provider/bin/ror_macos_openal_smoke_tests")
set_tests_properties(macos_openal_smoke PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;793;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
