#!/bin/sh

ror_launcher_dir=$(
    CDPATH='' cd -P "$(dirname "$0")" 2>/dev/null && pwd -P
) || exit 1

if [ -n "${LD_LIBRARY_PATH:-}" ]; then
    LD_LIBRARY_PATH="${ror_launcher_dir}/lib:${LD_LIBRARY_PATH}"
else
    LD_LIBRARY_PATH="${ror_launcher_dir}/lib"
fi
export LD_LIBRARY_PATH

exec "${ror_launcher_dir}/RoR" "$@"
