/*
    This source file is part of Rigs of Rods

    Rigs of Rods is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License version 3.
*/

/// @file
/// @brief Renderer-neutral, source-authoritative managed-material declarations.

#pragma once

#include "RenderPayloadDigest.h"
#include "RenderValidation.h"

#include <array>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>

namespace RoR::Render {

class Ogre14ManagedMaterialSourceAdapter;

constexpr std::uint32_t kManagedMaterialSourceReceiptVersion = 1U;
constexpr std::uint32_t kManagedMaterialDeclarationVersion = 1U;
constexpr std::uint32_t kManagedMaterialDeclarationRegistryVersion = 1U;
constexpr std::uint32_t kManagedMaterialDeclarationSnapshotVersion = 1U;

constexpr std::size_t kManagedMaterialTextureSlotCount = 3U;
constexpr std::size_t kManagedMaterialMaximumDeclarationsPerActor = 4096U;
constexpr std::size_t kManagedMaterialMaximumIdentifierBytes = 16384U;
constexpr std::uint64_t kManagedMaterialMaximumSourceBytes =
    512ULL * 1024ULL * 1024ULL;
constexpr std::uint64_t kManagedMaterialMaximumRetainedSourceBytes =
    1024ULL * 1024ULL * 1024ULL;
constexpr std::uint64_t kManagedMaterialMaximumRetainedIdentityBytes =
    16ULL * 1024ULL * 1024ULL;

/// Exact RigDef managed-material families. These are semantic inputs for a
/// future renderer lowering, not a description of any legacy OGRE pass.
enum class ManagedMaterialSemanticType : std::uint8_t {
  FLEXMESH_STANDARD = 1U,
  FLEXMESH_TRANSPARENT = 2U,
  MESH_STANDARD = 3U,
  MESH_TRANSPARENT = 4U,
};

enum class ManagedMaterialTextureSlot : std::uint8_t {
  DIFFUSE = 0U,
  SPECULAR = 1U,
  DAMAGED_DIFFUSE = 2U,
};

/// Trust is stated explicitly. Ordinary package selection is byte-exact but
/// unauthenticated; authenticated generated bytes remain distinguishable from
/// authenticated archive bytes.
enum class ManagedMaterialSourceTrust : std::uint8_t {
  CALLER_SUPPLIED_UNAUTHENTICATED_BYTES = 1U,
  OBSERVED_SELECTED_SOURCE = 2U,
  AUTHENTICATED_ARCHIVE_MEMBER = 3U,
  AUTHENTICATED_GENERATED_FALLBACK = 4U,
};

struct ManagedMaterialDeclarationRegistryConfiguration final {
  std::uint32_t version = kManagedMaterialDeclarationRegistryVersion;
  std::size_t maximum_declarations =
      kManagedMaterialMaximumDeclarationsPerActor;
  std::uint64_t maximum_source_bytes = kManagedMaterialMaximumSourceBytes;
  std::uint64_t maximum_retained_source_bytes =
      kManagedMaterialMaximumRetainedSourceBytes;
  std::uint64_t maximum_retained_identity_bytes =
      kManagedMaterialMaximumRetainedIdentityBytes;
};

/// Sanitized serialization, diagnostic, and cache identity. Deliberately
/// absent: native pointers, handles, stream addresses, and GPU storage. These
/// value fields cannot recreate live source authority; renderer use must also
/// retain and revalidate the opaque edge binding issued by the source owner.
struct ManagedMaterialTextureSourceIdentity final {
  std::uint32_t version = kManagedMaterialSourceReceiptVersion;
  ManagedMaterialSourceTrust trust =
      ManagedMaterialSourceTrust::CALLER_SUPPLIED_UNAUTHENTICATED_BYTES;
  std::uint64_t group_generation = 0U;
  std::string effective_resource_group;
  std::string archive_identity;
  std::string archive_name;
  std::string archive_type;
  std::string archive_sha256;
  std::string exact_member_name;
  std::string exact_resource_name;
  std::string generated_rule;
  std::uint32_t generated_rule_version = 0U;
  std::uint64_t byte_count = 0U;
  RenderPayloadDigest source_sha256{};
};

enum class ManagedMaterialDeclarationTransactionStage : std::uint8_t {
  AFTER_SOURCE_BYTES_COPIED = 0U,
  BEFORE_SOURCE_RECEIPT_COMMIT = 1U,
  BEFORE_DECLARATION_COMMIT = 2U,
  BEFORE_REGISTRY_COMMIT = 3U,
  BEFORE_GENERATION_TRANSITION_COMMIT = 4U,
  BEFORE_SNAPSHOT_COMMIT = 5U,
};

class IManagedMaterialDeclarationFaultInjector {
public:
  virtual ~IManagedMaterialDeclarationFaultInjector() = default;
  virtual void BeforeManagedMaterialDeclarationStage(
      ManagedMaterialDeclarationTransactionStage) {}
};

class ManagedMaterialTextureSourceReceipt final {
public:
  ManagedMaterialTextureSourceReceipt() = default;
  ~ManagedMaterialTextureSourceReceipt() = default;
  ManagedMaterialTextureSourceReceipt(
      const ManagedMaterialTextureSourceReceipt &) noexcept = default;
  ManagedMaterialTextureSourceReceipt &operator=(
      const ManagedMaterialTextureSourceReceipt &) noexcept = default;
  ManagedMaterialTextureSourceReceipt(
      ManagedMaterialTextureSourceReceipt &&) noexcept = default;
  ManagedMaterialTextureSourceReceipt &operator=(
      ManagedMaterialTextureSourceReceipt &&) noexcept = default;

  [[nodiscard]] bool initialized() const noexcept;
  [[nodiscard]] const ManagedMaterialTextureSourceIdentity *identity()
      const noexcept;
  [[nodiscard]] const std::uint8_t *source_bytes() const noexcept;
  [[nodiscard]] std::size_t source_size() const noexcept;
  [[nodiscard]] std::uint64_t retained_identity_bytes() const noexcept;
  [[nodiscard]] RenderPayloadDigest canonical_identity_sha256() const noexcept;
  [[nodiscard]] bool SharesImmutableStateWith(
      const ManagedMaterialTextureSourceReceipt &other) const noexcept;

private:
  struct State;
  explicit ManagedMaterialTextureSourceReceipt(
      std::shared_ptr<const State> state) noexcept;
  std::shared_ptr<const State> state_;

  [[nodiscard]] static ValidationResult BuildFromTrustedIssuer(
      const ManagedMaterialDeclarationRegistryConfiguration &,
      const ManagedMaterialTextureSourceIdentity &, const void *, std::size_t,
      ManagedMaterialTextureSourceReceipt &,
      IManagedMaterialDeclarationFaultInjector *);

  friend ValidationResult BuildManagedMaterialTextureSourceReceipt(
      const ManagedMaterialDeclarationRegistryConfiguration &,
      const ManagedMaterialTextureSourceIdentity &, const void *, std::size_t,
      ManagedMaterialTextureSourceReceipt &,
      IManagedMaterialDeclarationFaultInjector *);
  friend class ManagedMaterialDeclaration;
  friend class ManagedMaterialDeclarationRegistry;
  friend class Ogre14ManagedMaterialSourceAdapter;
};

struct ManagedMaterialTextureBindingInput final {
  ManagedMaterialTextureSlot slot = ManagedMaterialTextureSlot::DIFFUSE;
  bool configured = false;
  std::string declared_texture_name;
  /// Post-Tuneup resource name requested from the resource manager.
  std::string resolved_texture_name;
  /// Exact name on the selected loaded texture; empty only when removed.
  std::string effective_texture_name;
  /// Post-Tuneup group requested from the resource manager.
  std::string requested_resource_group;
  /// Exact group on the selected loaded texture; empty only when Tuneup
  /// removal intentionally prevents source resolution.
  std::string effective_resource_group;
  ManagedMaterialTextureSourceReceipt source_receipt;
};

struct ManagedMaterialTextureBindingMetadata final {
  ManagedMaterialTextureSlot slot = ManagedMaterialTextureSlot::DIFFUSE;
  bool configured = false;
  std::string declared_texture_name;
  std::string resolved_texture_name;
  std::string effective_texture_name;
  std::string requested_resource_group;
  std::string effective_resource_group;
  bool source_receipt_present = false;
};

struct ManagedMaterialDeclarationInput final {
  std::uint32_t version = kManagedMaterialDeclarationVersion;
  std::uint64_t actor_generation = 0U;
  std::uint64_t definition_generation = 0U;
  std::string exact_material_name;
  ManagedMaterialSemanticType declared_type =
      ManagedMaterialSemanticType::FLEXMESH_STANDARD;
  ManagedMaterialSemanticType resolved_type =
      ManagedMaterialSemanticType::FLEXMESH_STANDARD;
  bool type_overridden_by_tuneup = false;
  bool double_sided = false;
  bool removed_by_tuneup = false;
  std::array<ManagedMaterialTextureBindingInput,
             kManagedMaterialTextureSlotCount>
      textures{};
};

struct ManagedMaterialDeclarationMetadata final {
  std::uint32_t version = kManagedMaterialDeclarationVersion;
  std::uint64_t actor_generation = 0U;
  std::uint64_t definition_generation = 0U;
  std::string exact_material_name;
  ManagedMaterialSemanticType declared_type =
      ManagedMaterialSemanticType::FLEXMESH_STANDARD;
  ManagedMaterialSemanticType resolved_type =
      ManagedMaterialSemanticType::FLEXMESH_STANDARD;
  bool type_overridden_by_tuneup = false;
  bool double_sided = false;
  bool removed_by_tuneup = false;
  std::array<ManagedMaterialTextureBindingMetadata,
             kManagedMaterialTextureSlotCount>
      textures{};
  RenderPayloadDigest canonical_identity_sha256{};
};

class ManagedMaterialDeclaration final {
public:
  ManagedMaterialDeclaration() = default;
  ~ManagedMaterialDeclaration() = default;
  ManagedMaterialDeclaration(const ManagedMaterialDeclaration &) noexcept =
      default;
  ManagedMaterialDeclaration &operator=(
      const ManagedMaterialDeclaration &) noexcept = default;
  ManagedMaterialDeclaration(ManagedMaterialDeclaration &&) noexcept = default;
  ManagedMaterialDeclaration &operator=(
      ManagedMaterialDeclaration &&) noexcept = default;

  [[nodiscard]] bool initialized() const noexcept;
  [[nodiscard]] const ManagedMaterialDeclarationMetadata *metadata()
      const noexcept;
  [[nodiscard]] const ManagedMaterialTextureSourceReceipt *source_receipt(
      ManagedMaterialTextureSlot slot) const noexcept;
  [[nodiscard]] std::uint64_t retained_identity_bytes() const noexcept;
  [[nodiscard]] bool SharesImmutableStateWith(
      const ManagedMaterialDeclaration &other) const noexcept;

private:
  struct State;
  explicit ManagedMaterialDeclaration(std::shared_ptr<const State> state)
      noexcept;
  std::shared_ptr<const State> state_;

  friend ValidationResult BuildManagedMaterialDeclaration(
      const ManagedMaterialDeclarationRegistryConfiguration &,
      const ManagedMaterialDeclarationInput &, ManagedMaterialDeclaration &,
      IManagedMaterialDeclarationFaultInjector *);
  friend class ManagedMaterialDeclarationRegistry;
  friend class ManagedMaterialDeclarationSnapshot;
};

class ManagedMaterialDeclarationSnapshot;

/// Per-actor immutable-snapshot registry. All mutations validate and allocate
/// a complete candidate before one noexcept shared-owner swap.
class ManagedMaterialDeclarationRegistry final {
public:
  ManagedMaterialDeclarationRegistry() = default;
  ~ManagedMaterialDeclarationRegistry() = default;
  ManagedMaterialDeclarationRegistry(
      const ManagedMaterialDeclarationRegistry &) noexcept = default;
  ManagedMaterialDeclarationRegistry &operator=(
      const ManagedMaterialDeclarationRegistry &) noexcept = default;
  ManagedMaterialDeclarationRegistry(
      ManagedMaterialDeclarationRegistry &&) noexcept = default;
  ManagedMaterialDeclarationRegistry &operator=(
      ManagedMaterialDeclarationRegistry &&) noexcept = default;

  [[nodiscard]] bool initialized() const noexcept;
  [[nodiscard]] bool active() const noexcept;
  [[nodiscard]] std::uint64_t actor_generation() const noexcept;
  [[nodiscard]] std::uint64_t next_definition_generation() const noexcept;
  [[nodiscard]] std::size_t size() const noexcept;
  [[nodiscard]] std::uint64_t retained_source_bytes() const noexcept;
  [[nodiscard]] std::uint64_t retained_identity_bytes() const noexcept;
  [[nodiscard]] bool SharesImmutableStateWith(
      const ManagedMaterialDeclarationRegistry &other) const noexcept;

private:
  struct State;
  explicit ManagedMaterialDeclarationRegistry(
      std::shared_ptr<const State> state) noexcept;
  std::shared_ptr<const State> state_;

  friend ValidationResult InitializeManagedMaterialDeclarationRegistry(
      const ManagedMaterialDeclarationRegistryConfiguration &, std::uint64_t,
      ManagedMaterialDeclarationRegistry &);
  friend ValidationResult CommitManagedMaterialDeclaration(
      const ManagedMaterialDeclaration &,
      ManagedMaterialDeclarationRegistry &,
      IManagedMaterialDeclarationFaultInjector *);
  friend ValidationResult ResetManagedMaterialDeclarationRegistry(
      std::uint64_t, std::uint64_t, ManagedMaterialDeclarationRegistry &,
      IManagedMaterialDeclarationFaultInjector *);
  friend ValidationResult TeardownManagedMaterialDeclarationRegistry(
      std::uint64_t, ManagedMaterialDeclarationRegistry &,
      IManagedMaterialDeclarationFaultInjector *);
  friend bool RevokeManagedMaterialDeclarationRegistry(
      std::uint64_t, ManagedMaterialDeclarationRegistry &) noexcept;
  friend ValidationResult CaptureManagedMaterialDeclarationSnapshot(
      const ManagedMaterialDeclarationRegistry &,
      ManagedMaterialDeclarationSnapshot &,
      IManagedMaterialDeclarationFaultInjector *);
  friend bool IsManagedMaterialDeclarationSnapshotCurrent(
      const ManagedMaterialDeclarationRegistry &,
      const ManagedMaterialDeclarationSnapshot &) noexcept;
  friend class ManagedMaterialDeclarationSnapshot;
};

/// Immutable, deterministic declaration-name-ordered view. Historical
/// snapshots retain bytes for safe in-flight ownership. Registry currency is
/// intentionally separate from renderer/source authority currency.
class ManagedMaterialDeclarationSnapshot final {
public:
  ManagedMaterialDeclarationSnapshot() = default;
  ~ManagedMaterialDeclarationSnapshot() = default;
  ManagedMaterialDeclarationSnapshot(
      const ManagedMaterialDeclarationSnapshot &) noexcept = default;
  ManagedMaterialDeclarationSnapshot &operator=(
      const ManagedMaterialDeclarationSnapshot &) noexcept = default;
  ManagedMaterialDeclarationSnapshot(
      ManagedMaterialDeclarationSnapshot &&) noexcept = default;
  ManagedMaterialDeclarationSnapshot &operator=(
      ManagedMaterialDeclarationSnapshot &&) noexcept = default;

  [[nodiscard]] bool initialized() const noexcept;
  [[nodiscard]] std::uint32_t version() const noexcept;
  [[nodiscard]] std::uint64_t actor_generation() const noexcept;
  [[nodiscard]] std::size_t size() const noexcept;
  [[nodiscard]] const ManagedMaterialDeclaration *at(
      std::size_t index) const noexcept;
  [[nodiscard]] const ManagedMaterialDeclaration *Find(
      const std::string &exact_material_name) const noexcept;
  [[nodiscard]] std::uint64_t retained_source_bytes() const noexcept;
  [[nodiscard]] std::uint64_t retained_identity_bytes() const noexcept;
  [[nodiscard]] bool SharesImmutableStateWith(
      const ManagedMaterialDeclarationSnapshot &other) const noexcept;

private:
  explicit ManagedMaterialDeclarationSnapshot(
      std::shared_ptr<const ManagedMaterialDeclarationRegistry::State> state)
      noexcept;
  std::shared_ptr<const ManagedMaterialDeclarationRegistry::State> state_;

  friend ValidationResult CaptureManagedMaterialDeclarationSnapshot(
      const ManagedMaterialDeclarationRegistry &,
      ManagedMaterialDeclarationSnapshot &,
      IManagedMaterialDeclarationFaultInjector *);
  friend bool IsManagedMaterialDeclarationSnapshotCurrent(
      const ManagedMaterialDeclarationRegistry &,
      const ManagedMaterialDeclarationSnapshot &) noexcept;
};

[[nodiscard]] bool IsKnownManagedMaterialSemanticType(
    ManagedMaterialSemanticType type) noexcept;
[[nodiscard]] bool IsKnownManagedMaterialTextureSlot(
    ManagedMaterialTextureSlot slot) noexcept;
[[nodiscard]] bool IsKnownManagedMaterialSourceTrust(
    ManagedMaterialSourceTrust trust) noexcept;

[[nodiscard]] ValidationResult
ValidateManagedMaterialDeclarationRegistryConfiguration(
    const ManagedMaterialDeclarationRegistryConfiguration &configuration);

/// Copies and hashes caller-supplied, explicitly unauthenticated source bytes.
/// This API never claims that OGRE selected or observed those bytes.
/// Authenticated trust can only be issued by the OGRE edge adapter from an
/// opaque registry-minted resolution that is current immediately before and
/// after the copy. Failure leaves output untouched.
[[nodiscard]] ValidationResult BuildManagedMaterialTextureSourceReceipt(
    const ManagedMaterialDeclarationRegistryConfiguration &configuration,
    const ManagedMaterialTextureSourceIdentity &identity,
    const void *source_bytes, std::size_t source_size,
    ManagedMaterialTextureSourceReceipt &output,
    IManagedMaterialDeclarationFaultInjector *fault_injector = nullptr);

/// Builds one complete declaration. Every configured texture on a live
/// material requires an immutable source receipt; a Tuneup-removed material
/// retains its resolved names/groups without claiming source authority.
[[nodiscard]] ValidationResult BuildManagedMaterialDeclaration(
    const ManagedMaterialDeclarationRegistryConfiguration &configuration,
    const ManagedMaterialDeclarationInput &input,
    ManagedMaterialDeclaration &output,
    IManagedMaterialDeclarationFaultInjector *fault_injector = nullptr);

[[nodiscard]] ValidationResult InitializeManagedMaterialDeclarationRegistry(
    const ManagedMaterialDeclarationRegistryConfiguration &configuration,
    std::uint64_t actor_generation,
    ManagedMaterialDeclarationRegistry &output);

[[nodiscard]] ValidationResult CommitManagedMaterialDeclaration(
    const ManagedMaterialDeclaration &declaration,
    ManagedMaterialDeclarationRegistry &registry,
    IManagedMaterialDeclarationFaultInjector *fault_injector = nullptr);

/// Reload/reset requires a strictly newer actor generation and publishes an
/// empty active generation atomically.
[[nodiscard]] ValidationResult ResetManagedMaterialDeclarationRegistry(
    std::uint64_t exact_actor_generation,
    std::uint64_t new_actor_generation,
    ManagedMaterialDeclarationRegistry &registry,
    IManagedMaterialDeclarationFaultInjector *fault_injector = nullptr);

/// Revocation/unload closes the exact generation by allocation-free owner
/// reset after an optional test hook. Do not use this potentially-throwing
/// diagnostic seam from a noexcept destruction path.
[[nodiscard]] ValidationResult TeardownManagedMaterialDeclarationRegistry(
    std::uint64_t exact_actor_generation,
    ManagedMaterialDeclarationRegistry &registry,
    IManagedMaterialDeclarationFaultInjector *fault_injector = nullptr);

/// Allocation-free owner tombstone for noexcept actor destruction. Returns
/// false without mutation unless it targets the exact active generation.
[[nodiscard]] bool RevokeManagedMaterialDeclarationRegistry(
    std::uint64_t exact_actor_generation,
    ManagedMaterialDeclarationRegistry &registry) noexcept;

[[nodiscard]] ValidationResult CaptureManagedMaterialDeclarationSnapshot(
    const ManagedMaterialDeclarationRegistry &registry,
    ManagedMaterialDeclarationSnapshot &output,
    IManagedMaterialDeclarationFaultInjector *fault_injector = nullptr);

/// Checks only whether a snapshot is the actor registry's current publication.
/// It does not recreate or validate ContentManager/renderer source authority.
[[nodiscard]] bool IsManagedMaterialDeclarationSnapshotCurrent(
    const ManagedMaterialDeclarationRegistry &registry,
    const ManagedMaterialDeclarationSnapshot &snapshot) noexcept;

} // namespace RoR::Render
