# This source file is part of Rigs of Rods.
# Fail closed if the source compiled into the native Metal N2 proof is not the
# exact clean relevant-source manifest recorded at configure time.

if (NOT DEFINED N2_REPOSITORY_ROOT OR
    NOT DEFINED N2_EXPECTED_SOURCE_MANIFEST_SHA256)
    message(FATAL_ERROR "Metal N2 source provenance inputs are missing")
endif ()

set(_ror_n2_relevant_source_paths
    source/main/gfx/render/ogrenext/OgreNextDisplayDomainUnlit.cpp
    source/main/gfx/render/ogrenext/OgreNextDisplayDomainUnlit.h
    tools/ogre_next_probe/media/Hlms/RoR/DisplayDomain/DisplayDomain_piece_ps.any
    tools/ogre_next_probe/audit_embedded_namespace.py
    tools/ogre_next_probe/embedded_namespace/RoROgreNextNamespaceRemap.h
    tools/ogre_next_probe/patches/0006-embedded-namespace-plugin-symbols.patch
    tools/ogre_next_probe/src/embedded_namespace/main.cpp
    tools/ogre_next_probe/src/embedded_namespace/metal_plugin_export_probe.mm
    tools/ogre_next_probe/src/embedded_namespace/n1_session_adapter.cpp
    tools/ogre_next_probe/src/embedded_namespace/presenter_link_adapter.cpp
    tools/ogre_next_probe/src/embedded_namespace/next_adapter.cpp
    tools/ogre_next_probe/src/embedded_namespace/ogre14_adapter.cpp
    CMakeLists.txt
    cmake/VerifyStbImageSource.cmake
    doc/nextgen/OGRE14_MATERIAL_SEMANTIC_CATALOG_V2.md
    cmake/OgreNextProductionPackage.cmake
    cmake/RendererLauncherPackageConfig.cmake
    cmake/macos/StageMacOSBundle.cmake
    cmake/conan/locks/ogre3d-14.5.2-linux-x86_64-release.lock
    cmake/conan/locks/ogre3d-14.5.2-macos-arm64-release.lock
    cmake/conan/locks/ogre3d-14.5.2-windows-x86_64-release.lock
    cmake/conan/locks/ror-ogre14-linux-x86_64-release.lock
    cmake/conan/locks/ror-ogre14-macos-arm64-release.lock
    cmake/conan/locks/ror-ogre14-windows-x86_64-release.lock
    cmake/conan/recipes/mygui/conanfile.py
    cmake/conan/recipes/ogre3d/conandata.yml
    cmake/conan/recipes/ogre3d/patches/14.5.2/archive-manager-load-rollback.patch
    cmake/conan/recipes/ogre3d/patches/14.5.2/terrain-composite-revision-metal-readback.patch
    cmake/conan/recipes/ogre3d/patches/14.5.2/exact-material-script-preopen.patch
    cmake/conan/recipes/ogre3d/patches/14.5.2/expose-shadow-material-declaration-names.patch
    cmake/conan/recipes/ogre3d/README.md
    cmake/conan/recipes/ogre3d/test_package/CMakeLists.txt
    cmake/conan/recipes/ogre3d/test_package/conanfile.py
    cmake/conan/recipes/ogre3d/test_package/src/ogre_material_script_preopen_probe.cpp
    cmake/conan/recipes/ogre3d/test_package/src/ogre_recipe_probe.cpp
    conanfile.py
    doc/nextgen/GRAPHICS_SCENE_SNAPSHOT_PRODUCER.md
    doc/nextgen/OGRE14_AUTHENTICATED_MATERIAL_SCRIPT_RECEIPT.md
    doc/nextgen/OGRE14_AUTHENTICATED_TEXTURE_RECEIPTS.md
    doc/nextgen/OGRE14_EXACT_MATERIAL_SCRIPT_PREOPEN.md
    doc/nextgen/OGRE14_TERRAIN_COMPOSITE_CAPTURE_RECEIPTS.md
    source/main/Application.cpp
    source/main/GameContext.cpp
    source/main/GameContext.h
    source/main/gfx/GfxActorCaptureInventory.h
    source/main/gfx/RendererBackendPolicy.cpp
    source/main/gfx/RendererBackendPolicy.h
    source/main/gfx/GfxScene.cpp
    source/main/gfx/GfxScene.h
    source/main/utils/MeshObject.cpp
    source/main/utils/MeshObject.h
    source/main/gfx/RendererStartupHandoff.cpp
    source/main/gfx/RendererStartupHandoff.h
    source/main/gfx/RendererStartupPlan.cpp
    source/main/gfx/RendererStartupPlan.h
    source/main/physics/Actor.cpp
    source/main/physics/ActorManager.cpp
    source/main/physics/ActorManager.h
    source/main/physics/ActorSpawner.cpp
    source/main/physics/ActorSpawner.h
    source/main/physics/ActorSpawnerFlow.cpp
    source/main/physics/collision/Collisions.cpp
    source/main/physics/flex/FlexBody.cpp
    source/main/physics/flex/FlexBody.h
    source/main/physics/flex/FlexFactory.cpp
    source/main/physics/flex/FlexFactory.h
    source/main/physics/flex/FlexMesh.cpp
    source/main/physics/flex/FlexMesh.h
    source/main/physics/flex/FlexMeshTopology.h
    source/main/physics/flex/FlexMeshWheel.cpp
    source/main/physics/flex/FlexMeshWheel.h
    source/main/physics/flex/FlexObj.cpp
    source/main/physics/flex/FlexObj.h
    source/main/physics/flex/Flexable.h
    source/main/terrain/ProceduralManager.cpp
    source/main/terrain/ProceduralManager.h
    source/main/terrain/ProceduralRoad.cpp
    source/main/terrain/ProceduralRoad.h
    source/main/terrain/TerrainObjectManager.cpp
    source/main/terrain/TerrainObjectManager.h
    source/main/terrain/Terrain.cpp
    source/main/terrain/Terrain.h
    source/main/main.cpp
    source/main/AppContext.cpp
    source/main/AppContext.h
    source/main/system/ApplicationFatalError.h
    source/main/system/RendererBridgeChannel.cpp
    source/main/system/RendererBridgeChannel.h
    source/main/system/RendererBridgeEndpoint.cpp
    source/main/system/RendererBridgeEndpoint.h
    source/main/system/RendererBridgeLaunchPlan.cpp
    source/main/system/RendererBridgeLaunchPlan.h
    source/main/system/RendererBridgeProcessSupervisor.cpp
    source/main/system/RendererBridgeProcessSupervisor.h
    source/main/system/RendererChildIntent.cpp
    source/main/system/RendererChildIntent.h
    source/main/system/RendererChildLauncher.cpp
    source/main/system/RendererChildLauncher.h
    source/main/system/RendererOgre14GameBridge.cpp
    source/main/system/RendererOgre14GameBridge.h
    source/main/system/RendererOgre14GameHostSession.cpp
    source/main/system/RendererOgre14GameHostSession.h
    source/main/system/RendererGameInputTarget.cpp
    source/main/system/RendererGameInputTarget.h
    source/main/system/RendererOgre14InputAdapter.cpp
    source/main/system/RendererOgre14InputAdapter.h
    source/main/system/RendererGameInputEngineTarget.cpp
    source/main/system/RendererGameInputEngineTarget.h
    source/main/system/RendererOgre14ProductSession.cpp
    source/main/system/RendererOgre14ProductSession.h
    source/main/system/RendererInProcessSession.cpp
    source/main/system/RendererInProcessSession.h
    source/main/system/detail/OgreNextDemoInProcessFramePolicy.cpp
    source/main/system/detail/OgreNextDemoInProcessFramePolicy.h
    source/main/utils/InputEngine.cpp
    source/main/utils/InputEngine.h
    doc/nextgen/OGRE14_PRODUCT_SESSION.md
    source/main/system/RendererSiblingPath.cpp
    source/main/system/RendererSiblingPath.h
    source/main/system/RendererPackagedMediaPath.cpp
    source/main/system/RendererPackagedMediaPath.h
    source/main/system/RendererPackageRuntimeProbe.cpp
    source/main/system/RendererPackageRuntimeProbe.h
    source/main/system/RendererOgreNextChild.cpp
    source/main/system/RendererOgreNextChild.h
    source/main/system/RendererOgreNextChildMain.cpp
    source/main/system/RendererOgreNextLiveSession.cpp
    source/main/system/RendererOgreNextLiveSession.h
    source/main/system/RendererOgreNextProductionSession.cpp
    source/main/system/RendererOgreNextProductionSession.h
    source/main/system/RendererOgreNextSdlWindowRuntime.cpp
    source/main/system/RendererOgreNextSdlWindowRuntime.h
    source/main/system/RendererOgreNextSdlWindowRuntimeCocoa.mm
    source/main/system/RendererOgreNextInProcessPresenter.cpp
    source/main/system/RendererOgreNextInProcessPresenter.h
    source/main/system/RendererOgreNextWindowHost.cpp
    source/main/system/RendererOgreNextWindowHost.h
    source/main/system/RendererLauncherMain.cpp
    source/main/system/RendererLauncherPackageConfig.h.in
    source/main/system/RendererPublicLauncher.cpp
    source/main/system/RendererPublicLauncher.h
    source/main/CMakeLists.txt
    source/main/resources/CacheSystem.cpp
    source/main/resources/ContentManager.cpp
    source/main/resources/ContentManager.h
    source/main/resources/LegacyMaterialCompatibilityPlan.cpp
    source/main/resources/LegacyMaterialCompatibilityPlan.h
    source/main/resources/LegacyMaterialScriptSanitizer.cpp
    source/main/resources/LegacyMaterialScriptSanitizer.h
    source/main/resources/terrn2_fileformat/TerrainBundleDependency.cpp
    source/main/resources/terrn2_fileformat/TerrainBundleDependency.h
    source/main/resources/terrn2_fileformat/TerrainBundleArchiveVerifier.cpp
    source/main/resources/terrn2_fileformat/TerrainBundleArchiveVerifier.h
    source/main/resources/tobj_fileformat/CityWorldNeoQ20Compatibility.cpp
    source/main/resources/tobj_fileformat/CityWorldNeoQ20Compatibility.h
    source/main/gfx/render
    source/main/gfx/ogre14/Ogre14LegacyNativeAssetExtractor.cpp
    source/main/gfx/ogre14/Ogre14LegacyNativeAssetExtractor.h
    source/main/gfx/ogre14/Ogre14LegacyNativeMaterialCaptureAuthority.cpp
    source/main/gfx/ogre14/Ogre14LegacyMaterialSemanticCatalogV2.cpp
    source/main/gfx/ogre14/Ogre14LegacyMaterialSemanticCatalogV2.h
    source/main/gfx/ogre14/Ogre14LegacyMaterialSemanticRegistry.cpp
    source/main/gfx/ogre14/Ogre14LegacyMaterialSemanticRegistry.h
    source/main/gfx/ogre14/Ogre14LegacyLiveMaterialCoordinator.cpp
    source/main/gfx/ogre14/Ogre14LegacyLiveMaterialCoordinator.h
    source/main/gfx/ogre14/Ogre14GraphicsScenePreparedMaterialBinding.cpp
    source/main/gfx/ogre14/Ogre14GraphicsScenePreparedMaterialBinding.h
    source/main/gfx/ogre14/Ogre14AuthenticatedMaterialScriptReceipt.cpp
    source/main/gfx/ogre14/Ogre14AuthenticatedMaterialScriptReceipt.h
    source/main/gfx/ogre14/Ogre14AuthenticatedArchiveLocationClosure.h
    source/main/gfx/ogre14/Ogre14AuthenticatedResourceThreadGate.h
    tests/CMakeLists.txt
    source/main/gfx/ogre14/Ogre14AuthenticatedTextureReceipt.cpp
    source/main/gfx/ogre14/Ogre14AuthenticatedTextureReceipt.h
    source/main/gfx/ogre14/Ogre14SelectedTextureSource.cpp
    source/main/gfx/ogre14/Ogre14SelectedTextureSource.h
    tests/gfx/ogre14/Ogre14SelectedTextureSourceTests.cpp
    source/main/gfx/ogre14/Ogre14TerrainCompositeCaptureReceipt.cpp
    source/main/gfx/ogre14/Ogre14TerrainCompositeCaptureReceipt.h
    source/main/gfx/ogre14/Ogre14TerrainCompositeNativeAdapter.cpp
    doc/nextgen/OGRE_NEXT_DEMO_PRIVATE_BRIDGE.md
    doc/nextgen/OGRE_NEXT_COMBINED_RUNTIME.md
    source/main/gfx/ogre14/detail/OgreNextDemoPrivatePolicy.cpp
    source/main/gfx/ogre14/detail/OgreNextDemoPrivatePolicy.h
    source/main/gfx/ogre14/detail/OgreNextDemoMaterialSource.cpp
    source/main/gfx/ogre14/detail/OgreNextDemoMaterialSource.h
    source/main/gfx/ogre14/detail/Ogre14ToOgreNextTerrainSource.cpp
    source/main/gfx/ogre14/detail/Ogre14ToOgreNextTerrainSource.h
    source/main/system/detail/OgreNextDemoFrameNormalization.cpp
    source/main/system/detail/OgreNextDemoFrameNormalization.h
    source/main/physics/Savegame.cpp
    tests/tools/test_renderer_suite_packaging_contract.py
    tests/gfx/GfxActorCaptureInventoryTests.cpp
    tests/system/ApplicationFatalShutdownContractTests.cpp
    tests/tools/test_ogre14_native_workflow_contract.py
    tests/gfx/ogre14/Ogre14LegacyMaterialSemanticCatalogV2Tests.cpp
    tests/gfx/ogre14/Ogre14LegacyMaterialSemanticRegistryTests.cpp
    tests/gfx/render/Ogre14SourceTextureDecoderTests.cpp
    tests/fixtures/gfx/ogre14/material-semantic-catalog-v2.synthetic.json
    tests/gfx/ogre14/Ogre14LegacyLiveMaterialCoordinatorTests.cpp
    tests/gfx/ogre14/Ogre14GraphicsScenePreparedMaterialBindingTests.cpp
    tests/gfx/ogre14/Ogre14AuthenticatedTextureReceiptTests.cpp
    tests/gfx/ogre14/Ogre14TerrainCompositeCaptureReceiptTests.cpp
    tests/gfx/ogre14/Ogre14TerrainCompositeNativeReadbackTests.cpp
    tests/gfx/ogre14/OgreNextDemoPrivatePolicyTests.cpp
    tests/gfx/ogre14/Ogre14AuthenticatedMaterialScriptReceiptTests.cpp
    tests/gfx/ogre14/Ogre14AuthenticatedArchiveLocationClosureTests.cpp
    tests/gfx/ogre14/Ogre14AuthenticatedMaterialScriptNativeIntegrationTests.cpp
    tests/resources/LegacyMaterialCompatibilityPlanTests.cpp
    tests/resources/CityWorldNeoQ20CompatibilityTests.cpp
    tests/resources/LegacyMaterialScriptSanitizerTests.cpp
    tests/resources/TerrainBundleDependencyTests.cpp
    tests/resources/TerrainBundleArchiveVerifierTests.cpp
    tests/tools/assert_ogre_recipe_graph.py
    tests/tools/test_ogre14_exact_material_script_preopen_recipe_contract.py
    tests/gfx/RendererBackendPolicyTests.cpp
    tests/gfx/RendererBridgeEndpointTests.cpp
    tests/gfx/RendererBridgeLaunchPlanTests.cpp
    tests/gfx/RendererBridgeChannelTests.cpp
    tests/gfx/RendererBridgeProcessFakeChild.cpp
    tests/gfx/RendererBridgeProcessSupervisorTests.cpp
    tests/gfx/RendererChildIntentTests.cpp
    tests/gfx/RendererChildLauncherFakeChild.cpp
    tests/gfx/RendererChildLauncherTests.cpp
    tests/gfx/RendererOgre14GameBridgeTests.cpp
    tests/gfx/RendererOgre14GameHostSessionTests.cpp
    tests/gfx/RendererInProcessSessionTests.cpp
    tests/gfx/RendererSiblingPathTests.cpp
    tests/gfx/RendererPackageRuntimeProbeTests.cpp
    tests/gfx/RendererOgreNextChildTests.cpp
    tests/gfx/RendererOgreNextLiveSessionTests.cpp
    tests/gfx/RendererOgreNextInProcessPresenterPolicyTests.cpp
    tests/gfx/RendererOgreNextWindowHostTests.cpp
    tests/gfx/RendererPublicLauncherLegacyChild.cpp
    tests/gfx/RendererPublicLauncherTests.cpp
    tests/cmake/VerifyRendererPublicBridgeExit.cmake
    tests/gfx/RendererStartupHandoffTests.cpp
    tests/gfx/RendererStartupPlanTests.cpp
    tests/gfx/render/RenderBridgeControlTransportTests.cpp
    tests/gfx/render/RendererFrontendTransportDispatcherTests.cpp
    tests/gfx/render/GraphicsSceneSnapshotProducerTests.cpp
    tests/gfx/render/Ogre14GraphicsSceneSourceTests.cpp
    tests/gfx/render/Ogre14LegacyAssetTranslatorTests.cpp
    tests/gfx/render/Ogre14LegacyMaterialClosureTests.cpp
    tests/gfx/ogre14/Ogre14LegacyNativeAssetExtractorCompileTests.cpp
    tests/gfx/render/Ogre14ParticleCaptureSourceTests.cpp
    tests/gfx/render/Ogre14ProceduralRoadSourceTests.cpp
    tests/tools/test_ogre14_particle_capture_contract.py
    tests/gfx/render/Ogre14RoadMaterialTransactionTests.cpp
    tests/physics/FlexMeshTopologyTests.cpp
    tests/physics/Ogre14FlexShadowLoadTests.cpp
    tests/physics/Ogre14MetalFlexShadowReadContractTests.cpp
    tests/gfx/render/Ogre14DynamicMaterialClosureTests.cpp
    tests/tools/test_ogre_next_child_runtime_contract.py
    tests/tools/test_ogre_next_embedded_namespace_contract.py
    tests/tools/test_ogre14_legacy_asset_translator_contract.py
    tests/tools/test_ogre14_legacy_material_closure_contract.py
    tests/tools/test_ogre14_road_material_transaction_contract.py
    tests/tools/test_ogre_next_metal_n2_contract.py
    tests/tools/test_ogre14_dynamic_material_closure_contract.py
    tests/tools/test_ogre14_material_semantic_registry_contract.py
    tests/tools/test_ogre14_source_texture_decoder_contract.py
    tests/tools/test_ogre14_material_semantic_catalog_v2.py
    tests/tools/test_ogre14_live_material_coordinator_contract.py
    tests/tools/test_ogre14_graphics_scene_prepared_material_binding_contract.py
    tests/tools/test_ogre14_authenticated_texture_receipt_contract.py
    tests/tools/test_ogre14_authenticated_material_script_receipt_contract.py
    tests/tools/test_ogre14_authenticated_texture_capture_bridge_contract.py
    tests/tools/test_ogre14_terrain_composite_recipe_contract.py
    tests/tools/test_ogre14_terrain_composite_capture_receipt_contract.py
    tests/tools/test_ogre_next_product_packaging_contract.py
    tests/tools/test_ogre_next_probe_contract.py
    tests/tools/test_ogre_next_probe_workflow.py
    tests/tools/test_ogre_next_window_host_contract.py
    tests/tools/test_ogre_next_window_presentation_contract.py
    tests/tools/test_ogre_next_window_run_loop_contract.py
    tools/ogre_next_probe
    tools/ogre14_runtime_audit.py
    tools/compile_ogre14_material_semantic_catalog_v2.py
    tools/run_ogre_next_probe.py
    tools/validate_ogre_next_frame_probe.py
    tools/verify_ogre_next_artifact_set.py
    tools/schemas/ogre14-material-semantic-catalog-v2.schema.json)
execute_process(
    COMMAND git status --porcelain=v1 --untracked-files=all --
            ${_ror_n2_relevant_source_paths}
    WORKING_DIRECTORY "${N2_REPOSITORY_ROOT}"
    RESULT_VARIABLE _ror_n2_status_result
    OUTPUT_VARIABLE _ror_n2_status
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_VARIABLE _ror_n2_status_error)
if (NOT _ror_n2_status_result EQUAL 0)
    message(FATAL_ERROR
        "Could not inspect Metal N2 relevant source state: "
        "${_ror_n2_status_error}")
endif ()
if (NOT _ror_n2_status STREQUAL "")
    message(FATAL_ERROR
        "Metal N2 provenance requires a clean relevant source set:\n"
        "${_ror_n2_status}")
endif ()

file(GLOB_RECURSE _ror_n2_relevant_source_files
    LIST_DIRECTORIES false
    RELATIVE "${N2_REPOSITORY_ROOT}"
    "${N2_REPOSITORY_ROOT}/source/main/gfx/render/*"
    "${N2_REPOSITORY_ROOT}/tools/ogre_next_probe/*")
list(APPEND _ror_n2_relevant_source_files
    "source/main/gfx/render/ogrenext/OgreNextDisplayDomainUnlit.cpp"
    "source/main/gfx/render/ogrenext/OgreNextDisplayDomainUnlit.h"
    "tools/ogre_next_probe/media/Hlms/RoR/DisplayDomain/DisplayDomain_piece_ps.any"
    "tools/ogre_next_probe/audit_embedded_namespace.py"
    "tools/ogre_next_probe/embedded_namespace/RoROgreNextNamespaceRemap.h"
    "tools/ogre_next_probe/patches/0006-embedded-namespace-plugin-symbols.patch"
    "tools/ogre_next_probe/src/embedded_namespace/main.cpp"
    "tools/ogre_next_probe/src/embedded_namespace/metal_plugin_export_probe.mm"
    "tools/ogre_next_probe/src/embedded_namespace/n1_session_adapter.cpp"
    "tools/ogre_next_probe/src/embedded_namespace/presenter_link_adapter.cpp"
    "tools/ogre_next_probe/src/embedded_namespace/next_adapter.cpp"
    "tools/ogre_next_probe/src/embedded_namespace/ogre14_adapter.cpp"
    "CMakeLists.txt"
    "cmake/VerifyStbImageSource.cmake"
    "doc/nextgen/OGRE14_MATERIAL_SEMANTIC_CATALOG_V2.md"
    "cmake/OgreNextProductionPackage.cmake"
    "cmake/RendererLauncherPackageConfig.cmake"
    "cmake/macos/StageMacOSBundle.cmake"
    "cmake/conan/locks/ogre3d-14.5.2-linux-x86_64-release.lock"
    "cmake/conan/locks/ogre3d-14.5.2-macos-arm64-release.lock"
    "cmake/conan/locks/ogre3d-14.5.2-windows-x86_64-release.lock"
    "cmake/conan/locks/ror-ogre14-linux-x86_64-release.lock"
    "cmake/conan/locks/ror-ogre14-macos-arm64-release.lock"
    "cmake/conan/locks/ror-ogre14-windows-x86_64-release.lock"
    "cmake/conan/recipes/mygui/conanfile.py"
    "cmake/conan/recipes/ogre3d/conandata.yml"
    "cmake/conan/recipes/ogre3d/patches/14.5.2/archive-manager-load-rollback.patch"
    "cmake/conan/recipes/ogre3d/patches/14.5.2/terrain-composite-revision-metal-readback.patch"
    "cmake/conan/recipes/ogre3d/patches/14.5.2/exact-material-script-preopen.patch"
    "cmake/conan/recipes/ogre3d/patches/14.5.2/expose-shadow-material-declaration-names.patch"
    "cmake/conan/recipes/ogre3d/README.md"
    "cmake/conan/recipes/ogre3d/test_package/CMakeLists.txt"
    "cmake/conan/recipes/ogre3d/test_package/conanfile.py"
    "cmake/conan/recipes/ogre3d/test_package/src/ogre_material_script_preopen_probe.cpp"
    "cmake/conan/recipes/ogre3d/test_package/src/ogre_recipe_probe.cpp"
    "conanfile.py"
    "doc/nextgen/GRAPHICS_SCENE_SNAPSHOT_PRODUCER.md"
    "doc/nextgen/OGRE14_AUTHENTICATED_MATERIAL_SCRIPT_RECEIPT.md"
    "doc/nextgen/OGRE14_AUTHENTICATED_TEXTURE_RECEIPTS.md"
    "doc/nextgen/OGRE14_EXACT_MATERIAL_SCRIPT_PREOPEN.md"
    "doc/nextgen/OGRE14_TERRAIN_COMPOSITE_CAPTURE_RECEIPTS.md"
    "source/main/Application.cpp"
    "source/main/GameContext.cpp"
    "source/main/GameContext.h"
    "source/main/gfx/GfxActorCaptureInventory.h"
    "source/main/gfx/RendererBackendPolicy.cpp"
    "source/main/gfx/RendererBackendPolicy.h"
    "source/main/gfx/GfxScene.cpp"
    "source/main/gfx/GfxScene.h"
    "source/main/utils/MeshObject.cpp"
    "source/main/utils/MeshObject.h"
    "source/main/gfx/RendererStartupHandoff.cpp"
    "source/main/gfx/RendererStartupHandoff.h"
    "source/main/gfx/RendererStartupPlan.cpp"
    "source/main/gfx/RendererStartupPlan.h"
    "source/main/physics/Actor.cpp"
    "source/main/physics/ActorManager.cpp"
    "source/main/physics/ActorManager.h"
    "source/main/physics/ActorSpawner.cpp"
    "source/main/physics/ActorSpawner.h"
    "source/main/physics/ActorSpawnerFlow.cpp"
    "source/main/physics/collision/Collisions.cpp"
    "source/main/physics/flex/FlexBody.cpp"
    "source/main/physics/flex/FlexBody.h"
    "source/main/physics/flex/FlexFactory.cpp"
    "source/main/physics/flex/FlexFactory.h"
    "source/main/physics/flex/FlexMesh.cpp"
    "source/main/physics/flex/FlexMesh.h"
    "source/main/physics/flex/FlexMeshTopology.h"
    "source/main/physics/flex/FlexMeshWheel.cpp"
    "source/main/physics/flex/FlexMeshWheel.h"
    "source/main/physics/flex/FlexObj.cpp"
    "source/main/physics/flex/FlexObj.h"
    "source/main/physics/flex/Flexable.h"
    "source/main/terrain/ProceduralManager.cpp"
    "source/main/terrain/ProceduralManager.h"
    "source/main/terrain/ProceduralRoad.cpp"
    "source/main/terrain/ProceduralRoad.h"
    "source/main/terrain/TerrainObjectManager.cpp"
    "source/main/terrain/TerrainObjectManager.h"
    "source/main/terrain/Terrain.cpp"
    "source/main/terrain/Terrain.h"
    "source/main/main.cpp"
    "source/main/AppContext.cpp"
    "source/main/AppContext.h"
    "source/main/system/ApplicationFatalError.h"
    "source/main/system/RendererBridgeChannel.cpp"
    "source/main/system/RendererBridgeChannel.h"
    "source/main/system/RendererBridgeEndpoint.cpp"
    "source/main/system/RendererBridgeEndpoint.h"
    "source/main/system/RendererBridgeLaunchPlan.cpp"
    "source/main/system/RendererBridgeLaunchPlan.h"
    "source/main/system/RendererBridgeProcessSupervisor.cpp"
    "source/main/system/RendererBridgeProcessSupervisor.h"
    "source/main/system/RendererChildIntent.cpp"
    "source/main/system/RendererChildIntent.h"
    "source/main/system/RendererChildLauncher.cpp"
    "source/main/system/RendererChildLauncher.h"
    "source/main/system/RendererOgre14GameBridge.cpp"
    "source/main/system/RendererOgre14GameBridge.h"
    "source/main/system/RendererOgre14GameHostSession.cpp"
    "source/main/system/RendererOgre14GameHostSession.h"
    "source/main/system/RendererGameInputTarget.cpp"
    "source/main/system/RendererGameInputTarget.h"
    "source/main/system/RendererOgre14InputAdapter.cpp"
    "source/main/system/RendererOgre14InputAdapter.h"
    "source/main/system/RendererGameInputEngineTarget.cpp"
    "source/main/system/RendererGameInputEngineTarget.h"
    "source/main/system/RendererOgre14ProductSession.cpp"
    "source/main/system/RendererOgre14ProductSession.h"
    "source/main/system/RendererInProcessSession.cpp"
    "source/main/system/RendererInProcessSession.h"
    "source/main/system/detail/OgreNextDemoInProcessFramePolicy.cpp"
    "source/main/system/detail/OgreNextDemoInProcessFramePolicy.h"
    "source/main/utils/InputEngine.cpp"
    "source/main/utils/InputEngine.h"
    "doc/nextgen/OGRE14_PRODUCT_SESSION.md"
    "source/main/system/RendererSiblingPath.cpp"
    "source/main/system/RendererSiblingPath.h"
    "source/main/system/RendererPackagedMediaPath.cpp"
    "source/main/system/RendererPackagedMediaPath.h"
    "source/main/system/RendererPackageRuntimeProbe.cpp"
    "source/main/system/RendererPackageRuntimeProbe.h"
    "source/main/system/RendererOgreNextChild.cpp"
    "source/main/system/RendererOgreNextChild.h"
    "source/main/system/RendererOgreNextChildMain.cpp"
    "source/main/system/RendererOgreNextLiveSession.cpp"
    "source/main/system/RendererOgreNextLiveSession.h"
    "source/main/system/RendererOgreNextProductionSession.cpp"
    "source/main/system/RendererOgreNextProductionSession.h"
    "source/main/system/RendererOgreNextSdlWindowRuntime.cpp"
    "source/main/system/RendererOgreNextSdlWindowRuntime.h"
    "source/main/system/RendererOgreNextSdlWindowRuntimeCocoa.mm"
    "source/main/system/RendererOgreNextInProcessPresenter.cpp"
    "source/main/system/RendererOgreNextInProcessPresenter.h"
    "source/main/system/RendererOgreNextWindowHost.cpp"
    "source/main/system/RendererOgreNextWindowHost.h"
    "source/main/system/RendererLauncherMain.cpp"
    "source/main/system/RendererLauncherPackageConfig.h.in"
    "source/main/system/RendererPublicLauncher.cpp"
    "source/main/system/RendererPublicLauncher.h"
    "source/main/CMakeLists.txt"
    "source/main/resources/CacheSystem.cpp"
    "source/main/resources/ContentManager.cpp"
    "source/main/resources/ContentManager.h"
    "source/main/resources/LegacyMaterialCompatibilityPlan.cpp"
    "source/main/resources/LegacyMaterialCompatibilityPlan.h"
    "source/main/resources/LegacyMaterialScriptSanitizer.cpp"
    "source/main/resources/LegacyMaterialScriptSanitizer.h"
    "source/main/resources/terrn2_fileformat/TerrainBundleDependency.cpp"
    "source/main/resources/terrn2_fileformat/TerrainBundleDependency.h"
    "source/main/resources/terrn2_fileformat/TerrainBundleArchiveVerifier.cpp"
    "source/main/resources/terrn2_fileformat/TerrainBundleArchiveVerifier.h"
    "source/main/resources/tobj_fileformat/CityWorldNeoQ20Compatibility.cpp"
    "source/main/resources/tobj_fileformat/CityWorldNeoQ20Compatibility.h"
    "source/main/gfx/ogre14/Ogre14LegacyNativeAssetExtractor.cpp"
    "source/main/gfx/ogre14/Ogre14LegacyNativeAssetExtractor.h"
    "source/main/gfx/ogre14/Ogre14LegacyNativeMaterialCaptureAuthority.cpp"
    "source/main/gfx/ogre14/Ogre14LegacyMaterialSemanticCatalogV2.cpp"
    "source/main/gfx/ogre14/Ogre14LegacyMaterialSemanticCatalogV2.h"
    "source/main/gfx/ogre14/Ogre14LegacyMaterialSemanticRegistry.cpp"
    "source/main/gfx/ogre14/Ogre14LegacyMaterialSemanticRegistry.h"
    "source/main/gfx/ogre14/Ogre14LegacyLiveMaterialCoordinator.cpp"
    "source/main/gfx/ogre14/Ogre14LegacyLiveMaterialCoordinator.h"
    "source/main/gfx/ogre14/Ogre14GraphicsScenePreparedMaterialBinding.cpp"
    "source/main/gfx/ogre14/Ogre14GraphicsScenePreparedMaterialBinding.h"
    "source/main/gfx/ogre14/Ogre14AuthenticatedMaterialScriptReceipt.cpp"
    "source/main/gfx/ogre14/Ogre14AuthenticatedMaterialScriptReceipt.h"
    "source/main/gfx/ogre14/Ogre14AuthenticatedArchiveLocationClosure.h"
    "source/main/gfx/ogre14/Ogre14AuthenticatedResourceThreadGate.h"
    "tests/CMakeLists.txt"
    "source/main/gfx/ogre14/Ogre14AuthenticatedTextureReceipt.cpp"
    "source/main/gfx/ogre14/Ogre14AuthenticatedTextureReceipt.h"
    "source/main/gfx/ogre14/Ogre14SelectedTextureSource.cpp"
    "source/main/gfx/ogre14/Ogre14SelectedTextureSource.h"
    "tests/gfx/ogre14/Ogre14SelectedTextureSourceTests.cpp"
    "source/main/gfx/ogre14/Ogre14TerrainCompositeCaptureReceipt.cpp"
    "source/main/gfx/ogre14/Ogre14TerrainCompositeCaptureReceipt.h"
    "source/main/gfx/ogre14/Ogre14TerrainCompositeNativeAdapter.cpp"
    "doc/nextgen/OGRE_NEXT_DEMO_PRIVATE_BRIDGE.md"
    "doc/nextgen/OGRE_NEXT_COMBINED_RUNTIME.md"
    "source/main/gfx/ogre14/detail/OgreNextDemoPrivatePolicy.cpp"
    "source/main/gfx/ogre14/detail/OgreNextDemoPrivatePolicy.h"
    "source/main/gfx/ogre14/detail/OgreNextDemoMaterialSource.cpp"
    "source/main/gfx/ogre14/detail/OgreNextDemoMaterialSource.h"
    "source/main/gfx/ogre14/detail/Ogre14ToOgreNextTerrainSource.cpp"
    "source/main/gfx/ogre14/detail/Ogre14ToOgreNextTerrainSource.h"
    "source/main/system/detail/OgreNextDemoFrameNormalization.cpp"
    "source/main/system/detail/OgreNextDemoFrameNormalization.h"
    "source/main/physics/Savegame.cpp"
    "tests/tools/test_renderer_suite_packaging_contract.py"
    "tests/gfx/GfxActorCaptureInventoryTests.cpp"
    "tests/system/ApplicationFatalShutdownContractTests.cpp"
    "tests/tools/test_ogre14_native_workflow_contract.py"
    "tests/gfx/ogre14/Ogre14LegacyMaterialSemanticCatalogV2Tests.cpp"
    "tests/gfx/ogre14/Ogre14LegacyMaterialSemanticRegistryTests.cpp"
    "tests/gfx/render/Ogre14SourceTextureDecoderTests.cpp"
    "tests/fixtures/gfx/ogre14/material-semantic-catalog-v2.synthetic.json"
    "tests/gfx/ogre14/Ogre14LegacyLiveMaterialCoordinatorTests.cpp"
    "tests/gfx/ogre14/Ogre14GraphicsScenePreparedMaterialBindingTests.cpp"
    "tests/gfx/ogre14/Ogre14AuthenticatedTextureReceiptTests.cpp"
    "tests/gfx/ogre14/Ogre14TerrainCompositeCaptureReceiptTests.cpp"
    "tests/gfx/ogre14/Ogre14TerrainCompositeNativeReadbackTests.cpp"
    "tests/gfx/ogre14/OgreNextDemoPrivatePolicyTests.cpp"
    "tests/gfx/ogre14/Ogre14AuthenticatedMaterialScriptReceiptTests.cpp"
    "tests/gfx/ogre14/Ogre14AuthenticatedArchiveLocationClosureTests.cpp"
    "tests/gfx/ogre14/Ogre14AuthenticatedMaterialScriptNativeIntegrationTests.cpp"
    "tests/resources/LegacyMaterialCompatibilityPlanTests.cpp"
    "tests/resources/CityWorldNeoQ20CompatibilityTests.cpp"
    "tests/resources/LegacyMaterialScriptSanitizerTests.cpp"
    "tests/resources/TerrainBundleDependencyTests.cpp"
    "tests/resources/TerrainBundleArchiveVerifierTests.cpp"
    "tests/tools/assert_ogre_recipe_graph.py"
    "tests/tools/test_ogre14_exact_material_script_preopen_recipe_contract.py"
    "tests/gfx/RendererBackendPolicyTests.cpp"
    "tests/gfx/RendererBridgeEndpointTests.cpp"
    "tests/gfx/RendererBridgeLaunchPlanTests.cpp"
    "tests/gfx/RendererBridgeChannelTests.cpp"
    "tests/gfx/RendererBridgeProcessFakeChild.cpp"
    "tests/gfx/RendererBridgeProcessSupervisorTests.cpp"
    "tests/gfx/RendererChildIntentTests.cpp"
    "tests/gfx/RendererChildLauncherFakeChild.cpp"
    "tests/gfx/RendererChildLauncherTests.cpp"
    "tests/gfx/RendererOgre14GameBridgeTests.cpp"
    "tests/gfx/RendererOgre14GameHostSessionTests.cpp"
    "tests/gfx/RendererInProcessSessionTests.cpp"
    "tests/gfx/RendererSiblingPathTests.cpp"
    "tests/gfx/RendererPackageRuntimeProbeTests.cpp"
    "tests/gfx/RendererOgreNextChildTests.cpp"
    "tests/gfx/RendererOgreNextLiveSessionTests.cpp"
    "tests/gfx/RendererOgreNextInProcessPresenterPolicyTests.cpp"
    "tests/gfx/RendererOgreNextWindowHostTests.cpp"
    "tests/gfx/RendererPublicLauncherLegacyChild.cpp"
    "tests/gfx/RendererPublicLauncherTests.cpp"
    "tests/cmake/VerifyRendererPublicBridgeExit.cmake"
    "tests/gfx/RendererStartupHandoffTests.cpp"
    "tests/gfx/RendererStartupPlanTests.cpp"
    "tests/gfx/render/RenderBridgeControlTransportTests.cpp"
    "tests/gfx/render/RendererFrontendTransportDispatcherTests.cpp"
    "tests/gfx/render/GraphicsSceneSnapshotProducerTests.cpp"
    "tests/gfx/render/Ogre14GraphicsSceneSourceTests.cpp"
    "tests/gfx/render/Ogre14LegacyAssetTranslatorTests.cpp"
    "tests/gfx/render/Ogre14LegacyMaterialClosureTests.cpp"
    "tests/gfx/ogre14/Ogre14LegacyNativeAssetExtractorCompileTests.cpp"
    "tests/gfx/render/Ogre14ParticleCaptureSourceTests.cpp"
    "tests/gfx/render/Ogre14ProceduralRoadSourceTests.cpp"
    "tests/tools/test_ogre14_particle_capture_contract.py"
    "tests/gfx/render/Ogre14RoadMaterialTransactionTests.cpp"
    "tests/physics/FlexMeshTopologyTests.cpp"
    "tests/physics/Ogre14FlexShadowLoadTests.cpp"
    "tests/physics/Ogre14MetalFlexShadowReadContractTests.cpp"
    "tests/gfx/render/Ogre14DynamicMaterialClosureTests.cpp"
    "tests/tools/test_ogre_next_child_runtime_contract.py"
    "tests/tools/test_ogre_next_embedded_namespace_contract.py"
    "tests/tools/test_ogre14_legacy_asset_translator_contract.py"
    "tests/tools/test_ogre14_legacy_material_closure_contract.py"
    "tests/tools/test_ogre14_road_material_transaction_contract.py"
    "tests/tools/test_ogre_next_metal_n2_contract.py"
    "tests/tools/test_ogre14_dynamic_material_closure_contract.py"
    "tests/tools/test_ogre14_material_semantic_registry_contract.py"
    "tests/tools/test_ogre14_source_texture_decoder_contract.py"
    "tests/tools/test_ogre14_material_semantic_catalog_v2.py"
    "tests/tools/test_ogre14_live_material_coordinator_contract.py"
    "tests/tools/test_ogre14_graphics_scene_prepared_material_binding_contract.py"
    "tests/tools/test_ogre14_authenticated_texture_receipt_contract.py"
    "tests/tools/test_ogre14_authenticated_material_script_receipt_contract.py"
    "tests/tools/test_ogre14_authenticated_texture_capture_bridge_contract.py"
    "tests/tools/test_ogre14_terrain_composite_recipe_contract.py"
    "tests/tools/test_ogre14_terrain_composite_capture_receipt_contract.py"
    "tests/tools/test_ogre_next_product_packaging_contract.py"
    "tests/tools/test_ogre_next_probe_contract.py"
    "tests/tools/test_ogre_next_probe_workflow.py"
    "tests/tools/test_ogre_next_window_host_contract.py"
    "tests/tools/test_ogre_next_window_presentation_contract.py"
    "tests/tools/test_ogre_next_window_run_loop_contract.py"
    "tools/run_ogre_next_probe.py"
    "tools/ogre14_runtime_audit.py"
    "tools/compile_ogre14_material_semantic_catalog_v2.py"
    "tools/validate_ogre_next_frame_probe.py"
    "tools/verify_ogre_next_artifact_set.py"
    "tools/schemas/ogre14-material-semantic-catalog-v2.schema.json")
list(FILTER _ror_n2_relevant_source_files EXCLUDE REGEX
    "(^|/)__pycache__/|\\.py[co]$|(^|/)\\.DS_Store$")
list(REMOVE_DUPLICATES _ror_n2_relevant_source_files)
list(SORT _ror_n2_relevant_source_files)
set(_ror_n2_source_manifest "")
foreach (_ror_n2_relative IN LISTS _ror_n2_relevant_source_files)
    set(_ror_n2_file "${N2_REPOSITORY_ROOT}/${_ror_n2_relative}")
    if (NOT EXISTS "${_ror_n2_file}" OR IS_SYMLINK "${_ror_n2_file}")
        message(FATAL_ERROR
            "Metal N2 relevant source is missing or indirect: "
            "${_ror_n2_relative}")
    endif ()
    if (_ror_n2_relative MATCHES "[;\\\\\"]")
        message(FATAL_ERROR
            "Metal N2 relevant source path cannot be attested: "
            "${_ror_n2_relative}")
    endif ()
    file(SIZE "${_ror_n2_file}" _ror_n2_source_size)
    file(SHA256 "${_ror_n2_file}" _ror_n2_source_sha256)
    string(APPEND _ror_n2_source_manifest
        "${_ror_n2_relative}|${_ror_n2_source_size}|"
        "${_ror_n2_source_sha256}\n")
endforeach ()
if (NOT _ror_n2_relevant_source_files)
    message(FATAL_ERROR "Metal N2 relevant-source manifest is empty")
endif ()
string(SHA256 _ror_n2_source_manifest_sha256 "${_ror_n2_source_manifest}")
if (NOT "${_ror_n2_source_manifest_sha256}" STREQUAL
    "${N2_EXPECTED_SOURCE_MANIFEST_SHA256}")
    message(FATAL_ERROR
        "Metal N2 relevant-source manifest changed after configuration")
endif ()
