# CMake generated Testfile for 
# Source directory: /Users/beshoyhanna/Development/rigs-of-rods/tests
# Build directory: /Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(render_display_metrics "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_render_display_metrics_tests")
set_tests_properties(render_display_metrics PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;734;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(sky_mode_availability "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_sky_mode_availability_tests")
set_tests_properties(sky_mode_availability PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;739;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(v0_post_process_math "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_v0_post_process_math_tests")
set_tests_properties(v0_post_process_math PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;744;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(local_light_budget "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_local_light_budget_tests")
set_tests_properties(local_light_budget PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;749;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(beam_axial_response "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_beam_axial_response_tests")
set_tests_properties(beam_axial_response PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;754;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(beam_rest_length_scale "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_beam_rest_length_scale_tests")
set_tests_properties(beam_rest_length_scale PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;759;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_counter_noise "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_deterministic_counter_noise_tests")
set_tests_properties(deterministic_counter_noise PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;764;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_fixed_step_cadence "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_deterministic_fixed_step_cadence_tests")
set_tests_properties(deterministic_fixed_step_cadence PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;769;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_scenario_schedule "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_deterministic_scenario_schedule_tests")
set_tests_properties(deterministic_scenario_schedule PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;774;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_contact_order "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_deterministic_contact_order_tests")
set_tests_properties(deterministic_contact_order PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;779;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_state_digest "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_deterministic_state_digest_tests")
set_tests_properties(deterministic_state_digest PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;784;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_state_trace "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_deterministic_state_trace_tests")
set_tests_properties(deterministic_state_trace PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;789;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_input_trace "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_deterministic_input_trace_tests")
set_tests_properties(deterministic_input_trace PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;794;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_input_trace_runtime "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_deterministic_input_trace_runtime_tests")
set_tests_properties(deterministic_input_trace_runtime PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;799;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(deterministic_vehicle_input "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_deterministic_vehicle_input_tests")
set_tests_properties(deterministic_vehicle_input PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;804;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(calibrated_beam_material "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_calibrated_beam_material_tests")
set_tests_properties(calibrated_beam_material PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;809;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(calibrated_beam_material_adapter "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_calibrated_beam_material_adapter_tests")
set_tests_properties(calibrated_beam_material_adapter PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;814;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(calibrated_beam_step_sensitivity "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_calibrated_beam_step_sensitivity_tests")
set_tests_properties(calibrated_beam_step_sensitivity PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;819;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(calibrated_beam_mesh_refinement "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_calibrated_beam_mesh_refinement_tests")
set_tests_properties(calibrated_beam_mesh_refinement PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;824;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(calibrated_beam_savegame "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_calibrated_beam_savegame_tests")
set_tests_properties(calibrated_beam_savegame PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;829;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(calibrated_beam_savegame_json "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_calibrated_beam_savegame_json_tests")
set_tests_properties(calibrated_beam_savegame_json PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;835;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(rigdef_calibrated_beam_material "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_rigdef_calibrated_beam_material_tests")
set_tests_properties(rigdef_calibrated_beam_material PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;841;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(rigdef_calibrated_beam_material_roundtrip_integration "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/RoR" "--internal-rigdef-calibrated-material-roundtrip" "/Users/beshoyhanna/Development/rigs-of-rods/tests/fixtures/rigdef/calibrated_beam_material_roundtrip.truck")
set_tests_properties(rigdef_calibrated_beam_material_roundtrip_integration PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;847;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(hydro_actuator_response "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_hydro_actuator_response_tests")
set_tests_properties(hydro_actuator_response PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;856;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(shader_compatibility_policy "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_shader_compatibility_policy_tests")
set_tests_properties(shader_compatibility_policy PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;861;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(legacy_material_script_sanitizer "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_legacy_material_script_sanitizer_tests")
set_tests_properties(legacy_material_script_sanitizer PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;866;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(legacy_material_compatibility_plan "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_legacy_material_compatibility_plan_tests")
set_tests_properties(legacy_material_compatibility_plan PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;871;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(terrain_bundle_archive_verifier "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_terrain_bundle_archive_verifier_tests")
set_tests_properties(terrain_bundle_archive_verifier PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;876;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(terrain_bundle_dependency "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_terrain_bundle_dependency_tests")
set_tests_properties(terrain_bundle_dependency PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;881;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(cityworld_neoq20_compatibility "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_cityworld_neoq20_compatibility_tests")
set_tests_properties(cityworld_neoq20_compatibility PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;886;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(cityworld_neoq_tree_compatibility "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_cityworld_neoq_tree_compatibility_tests")
set_tests_properties(cityworld_neoq_tree_compatibility PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;891;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(cityworld_penguin_road_compatibility "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_cityworld_penguin_road_compatibility_tests")
set_tests_properties(cityworld_penguin_road_compatibility PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;896;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(terrain_bundle_config_syntax "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_terrain_bundle_config_syntax_tests")
set_tests_properties(terrain_bundle_config_syntax PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;902;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(beamng_package_manifest "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_beamng_package_manifest_tests")
set_tests_properties(beamng_package_manifest PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;908;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(beamng_material_inventory "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_beamng_material_inventory_tests")
set_tests_properties(beamng_material_inventory PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;913;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(beamng_zip_archive_index "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_beamng_zip_archive_index_tests")
set_tests_properties(beamng_zip_archive_index PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;918;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(beamng_zip_index_help "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_beamng_zip_index" "--help")
set_tests_properties(beamng_zip_index_help PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;923;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(beamng_formulacoupe_opt_in "/opt/homebrew/bin/cmake" "-DROR_BEAMNG_ZIP_INDEX_TOOL=/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_beamng_zip_index" "-P" "/Users/beshoyhanna/Development/rigs-of-rods/tests/resources/FormulaCoupeOptIn.cmake")
set_tests_properties(beamng_formulacoupe_opt_in PROPERTIES  SKIP_REGULAR_EXPRESSION "SKIP: FormulaCOUPE fixture is not explicitly supplied" _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;928;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(jbeam_expression_evaluator "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_jbeam_expression_evaluator_tests")
set_tests_properties(jbeam_expression_evaluator PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;943;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(jbeam_syntax "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_jbeam_syntax_tests")
set_tests_properties(jbeam_syntax PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;948;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(jbeam_coordinate_transform "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_jbeam_coordinate_transform_tests")
set_tests_properties(jbeam_coordinate_transform PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;953;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(jbeam_advanced_structure_ir "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_jbeam_advanced_structure_ir_tests")
set_tests_properties(jbeam_advanced_structure_ir PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;958;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(jbeam_part_resolver "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_jbeam_part_resolver_tests")
set_tests_properties(jbeam_part_resolver PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;963;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(jbeam_pressure_wheel_ir "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_jbeam_pressure_wheel_ir_tests")
set_tests_properties(jbeam_pressure_wheel_ir PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;968;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(jbeam_structural_ir "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_jbeam_structural_ir_tests")
set_tests_properties(jbeam_structural_ir PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;973;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(jbeam_to_rigdef "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_jbeam_to_rigdef_tests")
set_tests_properties(jbeam_to_rigdef PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;978;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(apple_executable_path "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_apple_executable_path_tests")
set_tests_properties(apple_executable_path PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;984;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(macos_user_directory_layout "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_macos_user_directory_layout_tests")
set_tests_properties(macos_user_directory_layout PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;988;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(macos_controller_contract "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_macos_controller_contract_tests")
set_tests_properties(macos_controller_contract PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;993;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(macos_input_bridge "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_macos_input_bridge_tests")
set_tests_properties(macos_input_bridge PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;997;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
add_test(macos_openal_smoke "/Users/beshoyhanna/Development/rigs-of-rods/build-macos-ogre14-roadmap/bin/ror_macos_openal_smoke_tests")
set_tests_properties(macos_openal_smoke PROPERTIES  _BACKTRACE_TRIPLES "/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;1003;add_test;/Users/beshoyhanna/Development/rigs-of-rods/tests/CMakeLists.txt;0;")
